void webServerInit() {
  // Set the URI's of the server
  restServer.onNotFound(serve404);
  restServer.on("/", servePage);
  restServer.begin();

  // Set up OTA on the server
  otaInit();

  // Debug
  Serial.println("[webServerInit] - Webserver was set up correctly");
}

void otaInit() {
  OTAServer.setup(&restServer, "/update");
}

void serve404() {
  restServer.send(404, "text/html", ""); 
}

void servePage() {
  // Search and replace:
    // find " and replace   \"                                    (no regex)
    // find ^ and replace     restServer.sendContent_P(PSTR("     (regex)
    // find $ and replace   \                                     (regex)
    // find $ and replace   n"));                                 (regex)

  // Debug 
  Serial.println("[servePage] - Serving webpage");

  // Set the bool 
  webSocketConnecting = true;

  restServer.sendHeader("Cache-Control", "no-cache, no-store, must-revalidate");
  restServer.sendHeader("Pragma", "no-cache");
  restServer.sendHeader("Expires", "-1");
  restServer.setContentLength(CONTENT_LENGTH_UNKNOWN);
  restServer.send(200, "text/html", ""); 

    restServer.sendContent_P(PSTR("<!DOCTYPE html>\n"));
  restServer.sendContent_P(PSTR("<html>\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("<head>\n"));
  restServer.sendContent_P(PSTR("    <!-- Global Data -->\n"));
  restServer.sendContent_P(PSTR("    <title>IoT Terrarium</title>\n"));
  restServer.sendContent_P(PSTR("    <meta charset='utf-8'>\n"));
  restServer.sendContent_P(PSTR("    <meta name='viewport' content='width=device-width, initial-scale=1'>\n"));
  restServer.sendContent_P(PSTR("    <link rel='icon' href='data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAA\n"));
  restServer.sendContent_P(PSTR("        ABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAAcAAAAHABznhikwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAA\n"));
  restServer.sendContent_P(PSTR("        AKISURBVDiNfZJLTBNRFIb/e2cKlEJheJWW8hSQgpiAqAgLwcSERBOjUQMh0SVLE5e6N25M1MSFGxYsiMGFrwWyMSbGYlREKCC\n"));
  restServer.sendContent_P(PSTR("        BkoI0pNIOLXTK9DHT48Y2oBnv8t7vfCf/OVeAwbkGCI6GBmu3q2LgVLt9qqVC2qo0FflPhMPaEkAZjhsJ8vtdo229JfM5ZuHB+\n"));
  restServer.sendContent_P(PSTR("        VvHa/Mswr3WnpJ587nWsYOc8E9np9Pc0W5351rMzr6RlmYlFC9KJjTOwIpODzZKvk8B1WWTRuySOL72K5Y6JIhEPEdSYmrS2St\n"));
  restServer.sendContent_P(PSTR("        07WyoNrvLCkebxL+/WEf3cBPXUgTfTMjSc6O5PrgY2/dshj5kI4TDC/1ENJNm6MwvzUXH5Sp8nfCBc4a8whxwDnx+5k11DzUWF\n"));
  restServer.sendContent_P(PSTR("        pTlMp6DmmwEWfZUM0bviahY3VMx/XoahZUmKDtJyOt72I8kEd1OgHRwq93M516tB0OrypNBOfJDBABBSN8hYsW6psM96caFK7e\n"));
  restServer.sendContent_P(PSTR("        R1nW0DABEBCICYwyMMUYgah3ihW/Z+KPFWOqNCABE/CpAEE0iHHU1OHvxktFykIzHmXfBkyeVlgee+/0qD4dniwEqywBEumExA\n"));
  restServer.sendContent_P(PSTR("        PiWl7AT3EZ0b1cGAK4oauIgIJo4kvH4fwQ/UNvUjOhuOAAAvLq6RwWwkgFsNXb4fWuGAsYYdE2DqsS+AH9+ImMYzQBV9U78XF0\n"));
  restServer.sendContent_P(PSTR("        2FJTYKrGxuhIL+HzurCAaVR4DmAMAe50Tm2teQ0F+QQFW5mZlZlKXAYBlHoLBbw5RFF8COHl/5C6sUumhwnRa1/Skvk8AApsb0\n"));
  restServer.sendContent_P(PSTR("        afvPjoBQMwA5eWdW0QTZyKRo8NmkR62WdLSX+lFQLQCwJRXWcrciocQdl0HMHaz61hfQpb7jWLEE1p26L8BSy8HR/A9I4AAAAA\n"));
  restServer.sendContent_P(PSTR("        ASUVORK5CYII=' type='image/x-png' />\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("    <!-- Apple Meta Tags -->\n"));
  restServer.sendContent_P(PSTR("    <meta name='apple-mobile-web-app-capable' content='yes'>\n"));
  restServer.sendContent_P(PSTR("    <meta name='apple-mobile-web-app-status-bar-style' content='black'>\n"));
  restServer.sendContent_P(PSTR("    <link rel='apple-touch-startup-image' href='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAA\n"));
  restServer.sendContent_P(PSTR("    BHNCSVQICAgIfAhkiAAAAA\n"));
  restServer.sendContent_P(PSTR("    lwSFlzAAADgAAAA4AB/Pg+8wAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABqpSURBVHic7Z15dBzFnce/1XNJo2sO6xwdo1uWZMn3\n"));
  restServer.sendContent_P(PSTR("    CdgQzOErCQSWYANJCEuS3SwQFgI5dklI8rLv8d7CPh67SSB5nIljroCBACEYYsBcvmVbt6zTOmd0azQzXfuHGHuqumeme2Z0jj5/aaqrq0vTv6n6XVVFsE\n"));
  restServer.sendContent_P(PSTR("    hQLi8oSDEQ97cJodcApBiAAUADKHmHUM+jrzZ1ts52HyOBzHYH5jLbi3KuJMBzACxy1wngFkHufa2h9eEZ7lrU0Mx2B+YqO4qydxOQfQASglTTEOCqYktK\n"));
  restServer.sendContent_P(PSTR("    Sv3A0Jsz1bdosigAMuwqzC6iRHgVQJyS+gTYUGxOqa13DJ2c5q5FnUUBkKHYmvIigBL/MnNOApbvsCNvRSqoSDHUM87cQwi2lKXq/6+2f2xyJvsaKYsCwL\n"));
  restServer.sendContent_P(PSTR("    GzMO8yEPof/mW2CjO23lGFJfYkmLMTkL8mDaJHRE/jkH81I6X64bqBwYMz2+PIEGa7AzPB9txc8xa7XdFwTgXxZ/6ftXoN1t9UAkHD6svLd9phyuLVA3r3\n"));
  restServer.sendContent_P(PSTR("    rtIlSaGesWULtNtzc81btkCrpE/TyYK1AnaVZpWKXu3dAL0aQPYXxR0A3hQgPPpKw9kjknuKc7eKlL7lX1a+NRurvpov+4yzh/vw/uOnmTIK/Pi1hrZf8X\n"));
  restServer.sendContent_P(PSTR("    V3lGTbIJIfALgawNIvip0EeJuK5Df7m1rfUfs/RoMFKQA7C3N+TAl+iimbXQ6REPp4nN51976a3pHz9xXlvEeBS3yftXoNvvrgasQl6eVboRT7f3UEjo5R\n"));
  restServer.sendContent_P(PSTR("    /9IBMubNebWzc+yLz2R7Ue69BPSnCGJREJBnhj3CbQdaWiaU/ZfRYcFNAduLcn5ECX6BwC8fAARKyT9PuOI+3Fmalw8AO0ps1f4vHwBKN2cFfvkAQAiWbc\n"));
  restServer.sendContent_P(PSTR("    vlSy0wCjcCwHUVqYk7C3OeJ6C/RnBzEhR0T6LWu3emp4UFpQTuLMhZA4I/QvnIlg5KbyyypnwsALcCZJXvgiAQXHxbGXSG4F9RSoYRzZ/0YHLM41cq5Jan\n"));
  restServer.sendContent_P(PSTR("    md+c9GjeBrBFxb9QahhK6a4bGPpUxT0RsaAEoMSa8jiAYv8y+6pUrNhlR8G6NAhaAc7OMYAytyUIwB6ALAOg8xXaqqwo2ZQR8pmEAG6XF+dqB/2LM0SR3g\n"));
  restServer.sendContent_P(PSTR("    LAztfPKDNhxZftKLk4E3FJevSfHQZl+7M8K9nyWIvT6eHvnQ5mXQuNFrtKlySJXlzhX1a0KQMbdl+QB1ulBYXr0vDe42fgGnGfL6dTL17nf2/xxtAv30fh\n"));
  restServer.sendContent_P(PSTR("    +nQc298KKjJv0uz/QdAQrLmuECWXZJ4vyywzITktDoeea/CvakvQuDcAeFdxByJgwegA1JOwBtyItuwqyfyM9BITrr53uYwJdwFjsh5ZFeaA1yX1TQZklQ\n"));
  restServer.sendContent_P(PSTR("    eub0jU4fLvVzIv30fRxgwYkzk9gwgbFD88QhaMAIB4C/w/GhJ0SLTK64FJS+Jw1T1VyF4mG+NBcqYRgqDOQLLmyZv/KZlGbPvhcqSXmGSvE4HAnJvIloHI\n"));
  restServer.sendContent_P(PSTR("    253TwMIRABDmDeiNwdUbnUGLzbeXI2/lEsm17jonGj/qVvzk/pZhnHq7XVJutiXiyruqkGgN7oPSx/MzMQ3pTIoW804H+EqZ3e7xeG4BEZxk1PM7n71NQZ\n"));
  restServer.sendContent_P(PSTR("    P9lX9tXGj9VhAILv5WGQRNHZo/7TlfTilw6Ll6JFgNyAjwy/UxPjiJ9357Gp5JL1NutiVi6x2VMCTqAtx5AZ2B/R0SSv2HBLJ9KjJZLhL6l9fr2z8O2aAK\n"));
  restServer.sendContent_P(PSTR("    5tUIsL0o9zqPx3sMIA+A0odh1LyAL9464UcAgzLZJgLBxltKkLeKHQlEL8X7j5/BcF9gv4xn0ou/P1aDUaeLKVfz8gFAy40AFCTZ9/f2otwHCMjTAO4XKP\n"));
  restServer.sendContent_P(PSTR("    lwR1H2fz4Qxfc2bwRgR3HOTwjonwGc/3IocNXO4tzvAwAIO2wqGQF8CALBRd8sQ3Ylq8i5Rtw4+MQZiF4qe9/nzzdhoG2EKUtOi1f18gFAp+deA5kaAbYX\n"));
  restServer.sendContent_P(PSTR("    5m0koD/27ypAHvisKHvvdRUVQTxUypkXArCzKOeXoHhQ7hql9Nc7S+xlfLnoEVU9QxAILrq1DKZs1jroOzuMY/tbJPVbj/ah7uA5pkwXp8Hm28tVvXwAMg\n"));
  restServer.sendContent_P(PSTR("    JG6BVV6QmEiE9C1ldDvjbuGnp51apV6h4kw5wXgB2F2bdR4EdBqsRT0fusCA0zCXsm1QkAMKUYXnp7OfRGdkg++VYHev1CvxMjbhx6toG9mRBc8u2lMGUa\n"));
  restServer.sendContent_P(PSTR("    VT/X4/JKivSj+ocAFAW57erMwZ7fqH4Yx5wWgJ1FtvUg5DG+PE76C1tJqHe5f4HMl6qIRGsc1t9YzBZSikN7GyB+4eg5/GIzXKNupkrF5dlBfQHBcPPCSm\n"));
  restServer.sendContent_P(PSTR("    EEwe3+RYYE3ZTbkeWb24tyvhvWQ79gzgrAzqwsIyA8A85SKVifhu33r5D8SgnIOv+BNFwBAIC8lUtQtIH1BDrbR3Hm3U70NA6i6WPWRLTkJGL5rrywnyfp\n"));
  restServer.sendContent_P(PSTR("    K0ER/EwaQoCLby3D2usLwEOAh7YV2EokFxQyZwVANGp/SIFC/7LsZRZs2FMCo9mAtf/EXAIFGNeNeyJ8AQCAldfmIy6JHWlOvNGKT59vZnz3RCBYv7tYkj\n"));
  restServer.sendContent_P(PSTR("    CiBpm+Mo6D0i1ZyCwzoXRzFqq2SwTNKAhC2FnJc1IAduXnpxPQe/zL4pJ12HhL6XkPXf6aNFknjg/XqBveMPQAHwajFiu5RJDJMQ8Gzg4zZaWXZMLKefLU\n"));
  restServer.sendContent_P(PSTR("    MuYInEaYnGbEii/bz3+u2paLtKJkvtrVOwvzLgvn2XNSAAQDuQNAvH/Zmq8VwsAN++tvLEaCSd7dSykw0h9ZbkXBunSYbYFfrtagQdV2abxBLcN947Llgk\n"));
  restServer.sendContent_P(PSTR("    Cw6Rsl0OovGAKEABv2FEOj5UYcIt6DMJhTAtDXd9TW23Pkv41Jxh/6l6cWJMO+OlVSX2/UYu2NxTK60RSD3WPyFxRCCFC1PSfg9bLNmVPKWQSMOV0B9ZXK\n"));
  restServer.sendContent_P(PSTR("    K3OwxC71CienGVF8ERtYosCVvuQWNcwJAXA4jtgdjmOPaDRC/ZkjJ+4ccgwy/ZKLovnIrjSjOEDcnnfShENO9RLZyKFGL2Dp5dkyd6ijv1W+j+acBLlso/\n"));
  restServer.sendContent_P(PSTR("    OUbM7iBZ+IXnq92ufPqgAMDx9LcziOPwFo6gHybwDiT3z0OVPHkKBD3orAcz0ArLq2AElLpAGXjhOOiPtICGQFLKPEJGeOqqbzlFNSptEJuPgbZUEVy5T0\n"));
  restServer.sendContent_P(PSTR("    eKQVpbB9nUqAVcWsCAClVHA4jt3s8Qg1AL4FP1Ov9ugppm5mmQkaXfBuag0abLy5VGInD3SMYMzhCnCXcvLXpUn6EOnQDwBUpGj+RBp1XL7LjhQFDqXsSk\n"));
  restServer.sendContent_P(PSTR("    k4e61aF/GMC4DTeWyl03niY4A8CVDmp00pRXtDC1PfKjMHypFWlIwKfkimwPtPnImov8CURWCrYL/swa7RALWVc/y1VokJmFaUjPLLshTdb82XfDfxE67h\n"));
  restServer.sendContent_P(PSTR("    Yrm6gZgxAaCUEofj2B2Uko8ArJarM9jvgGuC1dzVmFjVO/NgtrHzdW/TEBoPKY/tB8LGZQgNtI1gfNAdoHZonO2jOPlWG1Omi9Pgom+UyXn8ZLHmJkrqUk\n"));
  restServer.sendContent_P(PSTR("    DqLQrCjAhAf399stN5Yi9AHgYQcIgackjnw6Bp2Rwa7ZTZxM+dn/65ESP9kU0FtkoL811TCvQ0DQa+IQheD8U/nqqVBIHWXFeIBEuwbHYWrV4DLT89Ehpc\n"));
  restServer.sendContent_P(PSTR("    YeKYdgFwOI6uEISx4wCuC1XX7ZI6RDQ6dR42sy0R1TtYb5l7wouPnq4Dn36rhvgUPZJSGdcE+lvCszKOv9YCZzs7heRUWVG4IV11WxL9SKRB1x/wTKsAOB\n"));
  restServer.sendContent_P(PSTR("    wntgDCAYAocpQLGmkSh9rcPACo2JqN1ALWW3auzonT73aqbssfCzcd9bcOBagZmN7GIdS83cGUxSXqpAEohRAuWEwEQdW8NG0C4HAc/wql9A34JXCEIj5B\n"));
  restServer.sendContent_P(PSTR("    qvmOBnGTBoIIBBtvZj1oAHDklRYMnpP3uimBT/x0dqlzNHlcXnzwVC2fPo51NxYhLlm9VeF1i5gYZpcPUJFK59EgTIsAOJ3HbwfwAiHKNljwYUlfAkHDdm\n"));
  restServer.sendContent_P(PSTR("    moJzxvXnJaPFZdwzrGvJMiDv4hcIZPyDbTWQF1DbtVRR0/e6EJw72sklu4Ph25y1VN2+cZ6ZuQTmtEVLVnUdQFYGDg2NcpxWPhtK036JGayc6Dzs7w3bnF\n"));
  restServer.sendContent_P(PSTR("    F2dKYvQDbSM48de2AHcEh3c2UYqgOYP+dNYMoOEDNoPIaDZg9ddUKe0Mct+NTos6NW1EVQCczmNfIoT8IZJ2CyvZ7K7WI31h626EABtvKpEEkU6+0Yo+Lq\n"));
  restServer.sendContent_P(PSTR("    qnhASL1CKZGAo9RU2OeXDo2QY2jEyADbuLJXkNajh7tJctoKT2pTMd/WraiJoADA6eXEMpeRnBV+WGpGJtNfN5pH8CAwH85UqIT9Fj7Q1sZpUoUnz4ZK3q\n"));
  restServer.sendContent_P(PSTR("    cLFGp5HY3a7R0Ev4Pv5jgyRzuHRLVtgZRMBURjLv6iaE/l1tO1ERgN7ew1miKO4HEFlgHMDKzeuh07MKUd3BrojatK9OlaR9D54bx5G/NKtqhxBAy2Xwus\n"));
  restServer.sendContent_P(PSTR("    aCC0DLZ71o+Zz9pfIx/nBo+qRXshZBpOI+te1ELACUUkGr1T4FIC3StgAgMTkJyy9ay5Q1ftTNb8KgmnU3FEnW4J0+0MWv6g2JllvEESz7eHxwEp/8iU0e\n"));
  restServer.sendContent_P(PSTR("    FQSCTd+UWihq8Li8OLH/LFdKz65p7HhPbVsRC8Dg4MmfA/hSpO34s+2ma5nPVKT4/EV1v1YeQ4IO6/dwuQOU4sOn6zA5rlyT1+rYFyeK8goKpcBHz9RJRo\n"));
  restServer.sendContent_P(PSTR("    jKK3OwJMA6QqXUvN2OMV73oHjoAUB1ClREAuB0nthKKb0/kjbkKKosRdVGNlzQddqBuvcjmwpslRZJaHd0YAKf7WtU3AbvmaQBvvL6g13oqGHnaGtuYtAY\n"));
  restServer.sendContent_P(PSTR("    vxL6modw8k2JFdMe78IT4bQXtgB0dn5mpJT+NpI2gnHT3bdDp2eH7M+eb0TXGVV+Dgmrri1AUiprzjUe6kbbMWXKs9vFvnF+XR8ADPeO4/MX2BFLoxOw6Z\n"));
  restServer.sendContent_P(PSTR("    bSiJJHR/oncOC3pyV+DAryg33t7WF5uMJ+eUaj/qeQ2QEjWmTkZuHa7+xhyrweigO/ORWREGgNGmy8qRSEczEferYeE8OhTTrPBDuk6+K4dX0ixQdP1koU\n"));
  restServer.sendContent_P(PSTR("    NKUx/kAM947jb4+cwPgg10eCl15raFWt/F24PQyGho6WeL3CcURo8nm9Xrz8+J9w4tBhiF55bbqn/RxGh1kzkJApJ0okGTljzkmMc/OoPl4rGR14+ttGmC\n"));
  restServer.sendContent_P(PSTR("    1mklLjmOXd40OTGHOy7eriNEhOYwNJanBPeDHSPyHnwXQB9DRApEoMgQiKjwXN+I9eqe0L6PQISwAcjuPvAAgrDdmft/a+gqcfinh10yLBoPR/9je23xHo\n"));
  restServer.sendContent_P(PSTR("    suopwOk8sRVRePkA0MZl/ywyDRBSHeyyagGglFmuHBGWNGu0mlokAAQkaOBDlSO6v//YegCbI+qRH7YCu6Tshn+9E4b48OfLWGfvo49gYvxCkEgEPR2kuj\n"));
  restServer.sendContent_P(PSTR("    oB0GjIf0SQVCPBli9ddLH+8itQWFEZvYfEEBNjo3jqoV8zZQLFqQDVp64rbXxo6GgJpbgqzL7Jkp5rg1bLetZaG1RFMxfx42x9HSj3C/VSMToC4PUKNyHK\n"));
  restServer.sendContent_P(PSTR("    m0trtRqkZbMp0O2NDQFqLxKKtoZ6vsg1ltvRFOweRQJAKSUAdofZr6DY8lnXaKv0n1hEIW0N7I+HAHUHDiBouFKRADidJzcDmJbNC7M4PUBGihdRSBs3fV\n"));
  restServer.sendContent_P(PSTR("    IEn/8B5SPA18PsU0hsBawAdLWexaQr8uVcsYh09AxuAQAKBYAQdhPmaMKPAKLXi87moNPWIjK4xsfR08mmm1MIkY8ATufxAkxj0CczL0eSCbyoB6inrbEB\n"));
  restServer.sendContent_P(PSTR("    VGQjlUJ0pgByadi9UoDeoEdqFhujb1u0BM5Te/Qw/veBn+CNPz4jecH+8LoTAdxxhqSQv6SQjiBK6bQKADDlEOpuu7Bqh1dmYpW2xgbcv/t6uCenoov958\n"));
  restServer.sendContent_P(PSTR("    5hz13/HqAu+64p0LCvpiZkfFuJDjDte9dnLZqCsnz45uvnXz4AfP5+4DMkpN8ZCTn8AyEEgNJ6A4DwN8BTCO8L6Gpphscd/tLrhUJTTQ3z2ZwaOO9WMgVQ\n"));
  restServer.sendContent_P(PSTR("    GrkAOBxjxZiBc4V4S8Dj8aCrlc96jT2aTrMCULC0Qraee3IS3W1c0E9ASBNwqlqwiwJKlTQSKdkFuSAC25VY1wPGRkbQ3c6+1Pyl5bJ1O5oa4eUyqigJHg\n"));
  restServer.sendContent_P(PSTR("    PwEVQARHFmBEAfZ4A1nV24Eet6QPOZU5LATkEAAZD5rrzxY0TRLyioABBCAu/PFmVsBayqwfu1Y42mU+zwH2dMQEaOfEq5jNncpDRLOJQVMGNn19gK2H8u\n"));
  restServer.sendContent_P(PSTR("    1mMCzWfYKTx/6VLJNOkjnBiAjxACMHOHF2XZ2R2+2psaJPNaLNGsUAEEpFMAiZ4AkBkTgGxuBJDVbGMEr9eD1nr2V51ftlS2rsfjQdfZFqaMgCiyAICQOk\n"));
  restServer.sendContent_P(PSTR("    Dkq32VkpWfC8ItvY7VaaC9sVESEQ00Asj5TMQQaWD+hHAEIYoZgMGJTzDCnMpmCceqJcDb/4JGg9xi+TMhZL4jaowbr1X6rBACQNRvoxEBEkWwMTYFgFcA\n"));
  restServer.sendContent_P(PSTR("    bfkFATOlZfwlLftqehXvqBFiCqAzKwCL2UEAgOZTyhVA3gRU6gL2EcoMjHy/dRVk2vkRQBrjjgWaa6UmYCD4KUBJEog/ocxA9TshRgBvCchluSx0+rvPYb\n"));
  restServer.sendContent_P(PSTR("    CfXaoeaASQzZ4SQqeBMdWDXSQE0hORpxFeBwBiTxFsOi39AeeXybuA5fInCRWjJwCUQrE2GQ0SkhORYmUPa461oBA//1tS02BaIr+RpJyONC4aoicAGs3M\n"));
  restServer.sendContent_P(PSTR("    CgAA2PJjOybQfIYdAfLLlXsAAbT/rUndFuZBBSApyd0EYEYzM2J9nQA/BQSKAAKyq6hUKYBASB1gtZsQKN9BKQpITMHGeklYdKEyMTYqSYQJNP8D0nWUam\n"));
  restServer.sendContent_P(PSTR("    IAPkLmBFJKP1DbaCTwI8DYyAj6z0W2O9h8ofnMGYnZW1AuLwBUFNHRxFoAIlUeA/ChQABI4EzEaYDXAYDYsQT4CKAhPh6ZuXbZut0d7cw+AEDopeByhBQA\n"));
  restServer.sendContent_P(PSTR("    r1erev/ZSEixmpBkYo8YiBU9gFcA7aVLIWjkUzLlvhOt3hv9ESA1tbyLEER+9JYKsuy8HhAblkDfOXY7+UAhYEB2H4VzancKBxQvDsVf1TYcCbxDKFY2ja\n"));
  restServer.sendContent_P(PSTR("    hcu+7834QQXHT1joB1peaxuhiAD0VbxBBCnqWU3hnOA8JBslCkPjYE4JpvfwfxxgScPvw5Nl21DdUbNwWsK50ClC0E4VEkACbTss8cjuMnAczI5j28KTg6\n"));
  restServer.sendContent_P(PSTR("    NISB3h5YgiyMWAgQQrBt983YtvvmoPUopWhvkmwGoXr+B1RsEUMpng3nAeEgFxNoq48NRVAJfV2dGBthA7U0zClAhQDQZwAo31c9AsypVhiT2OPvYkUPUI\n"));
  restServer.sendContent_P(PSTR("    KcWayj7ukVAKu1up0QEvamxGrJ4nIDFjePuoDMd9H/UmN3Tzhtqdop1OsVHkQYhxKEgzQ9bGELwJt7n8Pd1+7CL793G/pCeD4lWUBATYCqIVG1UaTVWnHK\n"));
  restServer.sendContent_P(PSTR("    4Tj+KoAvh/tApfDrBBbyFNBYcxKP/uS+858nJybws98/HbA+/13QMDyAPlTvFUwI/Tkw/dnCfHbQYH8/hhwD0/3YWeHIB/9gPneE2COpnd8OTlAfA/ChWg\n"));
  restServer.sendContent_P(PSTR("    BMpurDAJ4P94FK4X0BwMKNCfAxgCx74B35Bnp7MDzIHpghkhkcAQDA49HeAWBa8wWtGamIM7InbCzUmAC/EDRoFrCMOawh4ZmAQJgCMBUfIA+G+1AlEEKQ\n"));
  restServer.sendContent_P(PSTR("    abcxZQtRACYnJtDJLe0KngUs0YWGXqltC/tY9LDPDEpJ6XsYwLFw71dCLKwTOFtfB9HLulfspYEFQGoCkrAtACACASDkUg+l5GYA4Z/HHoJY2EeYX9cXZ0\n"));
  restServer.sendContent_P(PSTR("    xAdmFhwPrSdQDhD/9AhEe+WSzLjlOKeyNpIxi8IjjQ042RQXUnfc51SquXo3z1mvOfr/vOv0CjCWydS0ZBGl4MwEf4R1d/gcVS9ajTeXwjpYj6fsJyB0q0\n"));
  restServer.sendContent_P(PSTR("    NTZg6cpV0X7UrCFoNPjVM3tx4tBHMFmXwB4kB2DIMYDBATbkL8zmCOBDFCe/CyDqrro0WwZ0BvbwyIW4TkCj0WL5pouDvnxAPizuFXWzLwAWy+pBQshVhO\n"));
  restServer.sendContent_P(PSTR("    Bc6NrKIYKArLzYzA6SQ0YHGnm9ubk1kjajduyrybSsURTJlQAiO9uVI9bXCfgjsQAITiNCr2xUz/21WJYdB4RrAERtw3/+PIGFaAkoJRrrAHiifvCz2Vz5\n"));
  restServer.sendContent_P(PSTR("    LkCvR5TMQ34E6OvqxPjojK5anzPwXsBw1gHwTMvJ32Zz9SuiSC8DoDpLlSeb2z+QUhqTeoAvLc6fOTkC+LBaqw+JorgZiGyJeVp2JnR69pDoWNQDZC2ACE\n"));
  restServer.sendContent_P(PSTR("    1AIMrHwMnhcJzKAzzPA1gdbhv33/A9tDdeWDOXmWdHZu60b2I+pxjo6UELu3PIeHxDW9K+CNP0InYEhcJsLj9L6bsbHA7rLwjBvQhD6NJzshgB6DrbItkb\n"));
  restServer.sendContent_P(PSTR("    L9agQEukLx+YxinAH0Iu9VgsVfcB+CoAh9r7Y2V1sBpIlFLzZkQAfJjNVX+hVLMcwEtq7ssrCRwciVkooqIITfsUwGOxVLQCuMbpPPYlgDxKKcpC3VO1cR\n"));
  restServer.sendContent_P(PSTR("    Ve+h27LEGv1UIQpl2FmRNQAK5JNmpICHkxGm3PuAD4MJmq32lr+3BlYmLiPQDuAmAKVDcrL1tStmPTCuTbFvZKIR+O4VH8/tUDTBkVxKhs3zOjUwBPTs7G\n"));
  restServer.sendContent_P(PSTR("    cbO56udutyYHoHcCkM2HNiYlINmcwpQNDI/ORBfnBI4h6f+qndRGJSo2qwLgIy2tYsRsrn7E5aLFAL2LEGmMOyOPTQ9zDMWON9AhFfbul1taohJzmRMC4C\n"));
  restServer.sendContent_P(PSTR("    Mjo3rUbK5+2GSqKhdFsZJS/BeAbgDIzGWngYGR2BkBBnhhp4haTHxOCYA/VuvyGoul6j6TaTKHEHIFpeIB/+tOmWFxoeIcZreCASFR275v1pRApRCy2g3g\n"));
  restServer.sendContent_P(PSTR("    7Z2FOQkg2OIrHxmbgNvjgU475/+FiOnnRwAiLvwRgEcUBEbqKQAH/8tYgLg9HoyNTzBlhCo7EUwJ80YAjPrERgDMIUJy2vFCwzE0Js34EDRRmwLmjQDsq6\n"));
  restServer.sendContent_P(PSTR("    mZJACzi6JjeOFbAgPS/9Ebp0sIvnhQBfNGAACAcsrPQEyMABIBaFZyKrhS5pUGRSmtJcA23+dz/YOobV3Yu4i29XArokn05n9gngkAwAZAHMMj2H/w8Gz1\n"));
  restServer.sendContent_P(PSTR("    ZVaglEZ1B/d5NQUIVJjx7evnGoREzwkEzDMB0HjJYUQx43g+IkI8FM325pUATPm/6a1AdBegzBOcFOS+1+s7jkaz0f8HLMVNFEf83NgAAAAASUVORK5CYI\n"));
  restServer.sendContent_P(PSTR("    I=' type='image/x-png' />\n"));
  restServer.sendContent_P(PSTR("    <link rel='apple-touch-icon' href='data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAA\n"));
  restServer.sendContent_P(PSTR("    ABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAAcAAAAHABznhikwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAA\n"));
  restServer.sendContent_P(PSTR("    AKISURBVDiNfZJLTBNRFIb/e2cKlEJheJWW8hSQgpiAqAgLwcSERBOjUQMh0SVLE5e6N25M1MSFGxYsiMGFrwWyMSbGYlREKCC\n"));
  restServer.sendContent_P(PSTR("    BkoI0pNIOLXTK9DHT48Y2oBnv8t7vfCf/OVeAwbkGCI6GBmu3q2LgVLt9qqVC2qo0FflPhMPaEkAZjhsJ8vtdo229JfM5ZuHB+\n"));
  restServer.sendContent_P(PSTR("    VvHa/Mswr3WnpJ587nWsYOc8E9np9Pc0W5351rMzr6RlmYlFC9KJjTOwIpODzZKvk8B1WWTRuySOL72K5Y6JIhEPEdSYmrS2St\n"));
  restServer.sendContent_P(PSTR("    07WyoNrvLCkebxL+/WEf3cBPXUgTfTMjSc6O5PrgY2/dshj5kI4TDC/1ENJNm6MwvzUXH5Sp8nfCBc4a8whxwDnx+5k11DzUWF\n"));
  restServer.sendContent_P(PSTR("    pTlMp6DmmwEWfZUM0bviahY3VMx/XoahZUmKDtJyOt72I8kEd1OgHRwq93M516tB0OrypNBOfJDBABBSN8hYsW6psM96caFK7e\n"));
  restServer.sendContent_P(PSTR("    R1nW0DABEBCICYwyMMUYgah3ihW/Z+KPFWOqNCABE/CpAEE0iHHU1OHvxktFykIzHmXfBkyeVlgee+/0qD4dniwEqywBEumExA\n"));
  restServer.sendContent_P(PSTR("    PiWl7AT3EZ0b1cGAK4oauIgIJo4kvH4fwQ/UNvUjOhuOAAAvLq6RwWwkgFsNXb4fWuGAsYYdE2DqsS+AH9+ImMYzQBV9U78XF0\n"));
  restServer.sendContent_P(PSTR("    2FJTYKrGxuhIL+HzurCAaVR4DmAMAe50Tm2teQ0F+QQFW5mZlZlKXAYBlHoLBbw5RFF8COHl/5C6sUumhwnRa1/Skvk8AApsb0\n"));
  restServer.sendContent_P(PSTR("    afvPjoBQMwA5eWdW0QTZyKRo8NmkR62WdLSX+lFQLQCwJRXWcrciocQdl0HMHaz61hfQpb7jWLEE1p26L8BSy8HR/A9I4AAAAA\n"));
  restServer.sendContent_P(PSTR("    ASUVORK5CYII=' type='image/x-png' />\n"));
  restServer.sendContent_P(PSTR("    <link rel='apple-touch-icon-precomposed' sizes='128x128' href='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAA\n"));
  restServer.sendContent_P(PSTR("    BHNCSVQICAgIfAhkiAAAAA\n"));
  restServer.sendContent_P(PSTR("    lwSFlzAAADgAAAA4AB/Pg+8wAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABqpSURBVHic7Z15dBzFnce/1XNJo2sO6xwdo1uWZMn3\n"));
  restServer.sendContent_P(PSTR("    CdgQzOErCQSWYANJCEuS3SwQFgI5dklI8rLv8d7CPh67SSB5nIljroCBACEYYsBcvmVbt6zTOmd0azQzXfuHGHuqumeme2Z0jj5/aaqrq0vTv6n6XVVFsE\n"));
  restServer.sendContent_P(PSTR("    hQLi8oSDEQ97cJodcApBiAAUADKHmHUM+jrzZ1ts52HyOBzHYH5jLbi3KuJMBzACxy1wngFkHufa2h9eEZ7lrU0Mx2B+YqO4qydxOQfQASglTTEOCqYktK\n"));
  restServer.sendContent_P(PSTR("    Sv3A0Jsz1bdosigAMuwqzC6iRHgVQJyS+gTYUGxOqa13DJ2c5q5FnUUBkKHYmvIigBL/MnNOApbvsCNvRSqoSDHUM87cQwi2lKXq/6+2f2xyJvsaKYsCwL\n"));
  restServer.sendContent_P(PSTR("    GzMO8yEPof/mW2CjO23lGFJfYkmLMTkL8mDaJHRE/jkH81I6X64bqBwYMz2+PIEGa7AzPB9txc8xa7XdFwTgXxZ/6ftXoN1t9UAkHD6svLd9phyuLVA3r3\n"));
  restServer.sendContent_P(PSTR("    rtIlSaGesWULtNtzc81btkCrpE/TyYK1AnaVZpWKXu3dAL0aQPYXxR0A3hQgPPpKw9kjknuKc7eKlL7lX1a+NRurvpov+4yzh/vw/uOnmTIK/Pi1hrZf8X\n"));
  restServer.sendContent_P(PSTR("    V3lGTbIJIfALgawNIvip0EeJuK5Df7m1rfUfs/RoMFKQA7C3N+TAl+iimbXQ6REPp4nN51976a3pHz9xXlvEeBS3yftXoNvvrgasQl6eVboRT7f3UEjo5R\n"));
  restServer.sendContent_P(PSTR("    /9IBMubNebWzc+yLz2R7Ue69BPSnCGJREJBnhj3CbQdaWiaU/ZfRYcFNAduLcn5ECX6BwC8fAARKyT9PuOI+3Fmalw8AO0ps1f4vHwBKN2cFfvkAQAiWbc\n"));
  restServer.sendContent_P(PSTR("    vlSy0wCjcCwHUVqYk7C3OeJ6C/RnBzEhR0T6LWu3emp4UFpQTuLMhZA4I/QvnIlg5KbyyypnwsALcCZJXvgiAQXHxbGXSG4F9RSoYRzZ/0YHLM41cq5Jan\n"));
  restServer.sendContent_P(PSTR("    md+c9GjeBrBFxb9QahhK6a4bGPpUxT0RsaAEoMSa8jiAYv8y+6pUrNhlR8G6NAhaAc7OMYAytyUIwB6ALAOg8xXaqqwo2ZQR8pmEAG6XF+dqB/2LM0SR3g\n"));
  restServer.sendContent_P(PSTR("    LAztfPKDNhxZftKLk4E3FJevSfHQZl+7M8K9nyWIvT6eHvnQ5mXQuNFrtKlySJXlzhX1a0KQMbdl+QB1ulBYXr0vDe42fgGnGfL6dTL17nf2/xxtAv30fh\n"));
  restServer.sendContent_P(PSTR("    +nQc298KKjJv0uz/QdAQrLmuECWXZJ4vyywzITktDoeea/CvakvQuDcAeFdxByJgwegA1JOwBtyItuwqyfyM9BITrr53uYwJdwFjsh5ZFeaA1yX1TQZklQ\n"));
  restServer.sendContent_P(PSTR("    eub0jU4fLvVzIv30fRxgwYkzk9gwgbFD88QhaMAIB4C/w/GhJ0SLTK64FJS+Jw1T1VyF4mG+NBcqYRgqDOQLLmyZv/KZlGbPvhcqSXmGSvE4HAnJvIloHI\n"));
  restServer.sendContent_P(PSTR("    253TwMIRABDmDeiNwdUbnUGLzbeXI2/lEsm17jonGj/qVvzk/pZhnHq7XVJutiXiyruqkGgN7oPSx/MzMQ3pTIoW804H+EqZ3e7xeG4BEZxk1PM7n71NQZ\n"));
  restServer.sendContent_P(PSTR("    P9lX9tXGj9VhAILv5WGQRNHZo/7TlfTilw6Ll6JFgNyAjwy/UxPjiJ9357Gp5JL1NutiVi6x2VMCTqAtx5AZ2B/R0SSv2HBLJ9KjJZLhL6l9fr2z8O2aAK\n"));
  restServer.sendContent_P(PSTR("    5tUIsL0o9zqPx3sMIA+A0odh1LyAL9464UcAgzLZJgLBxltKkLeKHQlEL8X7j5/BcF9gv4xn0ou/P1aDUaeLKVfz8gFAy40AFCTZ9/f2otwHCMjTAO4XKP\n"));
  restServer.sendContent_P(PSTR("    lwR1H2fz4Qxfc2bwRgR3HOTwjonwGc/3IocNXO4tzvAwAIO2wqGQF8CALBRd8sQ3Ylq8i5Rtw4+MQZiF4qe9/nzzdhoG2EKUtOi1f18gFAp+deA5kaAbYX\n"));
  restServer.sendContent_P(PSTR("    5m0koD/27ypAHvisKHvvdRUVQTxUypkXArCzKOeXoHhQ7hql9Nc7S+xlfLnoEVU9QxAILrq1DKZs1jroOzuMY/tbJPVbj/ah7uA5pkwXp8Hm28tVvXwAMg\n"));
  restServer.sendContent_P(PSTR("    JG6BVV6QmEiE9C1ldDvjbuGnp51apV6h4kw5wXgB2F2bdR4EdBqsRT0fusCA0zCXsm1QkAMKUYXnp7OfRGdkg++VYHev1CvxMjbhx6toG9mRBc8u2lMGUa\n"));
  restServer.sendContent_P(PSTR("    VT/X4/JKivSj+ocAFAW57erMwZ7fqH4Yx5wWgJ1FtvUg5DG+PE76C1tJqHe5f4HMl6qIRGsc1t9YzBZSikN7GyB+4eg5/GIzXKNupkrF5dlBfQHBcPPCSm\n"));
  restServer.sendContent_P(PSTR("    EEwe3+RYYE3ZTbkeWb24tyvhvWQ79gzgrAzqwsIyA8A85SKVifhu33r5D8SgnIOv+BNFwBAIC8lUtQtIH1BDrbR3Hm3U70NA6i6WPWRLTkJGL5rrywnyfp\n"));
  restServer.sendContent_P(PSTR("    K0ER/EwaQoCLby3D2usLwEOAh7YV2EokFxQyZwVANGp/SIFC/7LsZRZs2FMCo9mAtf/EXAIFGNeNeyJ8AQCAldfmIy6JHWlOvNGKT59vZnz3RCBYv7tYkj\n"));
  restServer.sendContent_P(PSTR("    CiBpm+Mo6D0i1ZyCwzoXRzFqq2SwTNKAhC2FnJc1IAduXnpxPQe/zL4pJ12HhL6XkPXf6aNFknjg/XqBveMPQAHwajFiu5RJDJMQ8Gzg4zZaWXZMLKefLU\n"));
  restServer.sendContent_P(PSTR("    MuYInEaYnGbEii/bz3+u2paLtKJkvtrVOwvzLgvn2XNSAAQDuQNAvH/Zmq8VwsAN++tvLEaCSd7dSykw0h9ZbkXBunSYbYFfrtagQdV2abxBLcN947Llgk\n"));
  restServer.sendContent_P(PSTR("    Cw6Rsl0OovGAKEABv2FEOj5UYcIt6DMJhTAtDXd9TW23Pkv41Jxh/6l6cWJMO+OlVSX2/UYu2NxTK60RSD3WPyFxRCCFC1PSfg9bLNmVPKWQSMOV0B9ZXK\n"));
  restServer.sendContent_P(PSTR("    K3OwxC71CienGVF8ERtYosCVvuQWNcwJAXA4jtgdjmOPaDRC/ZkjJ+4ccgwy/ZKLovnIrjSjOEDcnnfShENO9RLZyKFGL2Dp5dkyd6ijv1W+j+acBLlso/\n"));
  restServer.sendContent_P(PSTR("    OUbM7iBZ+IXnq92ufPqgAMDx9LcziOPwFo6gHybwDiT3z0OVPHkKBD3orAcz0ArLq2AElLpAGXjhOOiPtICGQFLKPEJGeOqqbzlFNSptEJuPgbZUEVy5T0\n"));
  restServer.sendContent_P(PSTR("    eKQVpbB9nUqAVcWsCAClVHA4jt3s8Qg1AL4FP1Ov9ugppm5mmQkaXfBuag0abLy5VGInD3SMYMzhCnCXcvLXpUn6EOnQDwBUpGj+RBp1XL7LjhQFDqXsSk\n"));
  restServer.sendContent_P(PSTR("    k4e61aF/GMC4DTeWyl03niY4A8CVDmp00pRXtDC1PfKjMHypFWlIwKfkimwPtPnImov8CURWCrYL/swa7RALWVc/y1VokJmFaUjPLLshTdb82XfDfxE67h\n"));
  restServer.sendContent_P(PSTR("    Yrm6gZgxAaCUEofj2B2Uko8ArJarM9jvgGuC1dzVmFjVO/NgtrHzdW/TEBoPKY/tB8LGZQgNtI1gfNAdoHZonO2jOPlWG1Omi9Pgom+UyXn8ZLHmJkrqUk\n"));
  restServer.sendContent_P(PSTR("    DqLQrCjAhAf399stN5Yi9AHgYQcIgackjnw6Bp2Rwa7ZTZxM+dn/65ESP9kU0FtkoL811TCvQ0DQa+IQheD8U/nqqVBIHWXFeIBEuwbHYWrV4DLT89Ehpc\n"));
  restServer.sendContent_P(PSTR("    YeKYdgFwOI6uEISx4wCuC1XX7ZI6RDQ6dR42sy0R1TtYb5l7wouPnq4Dn36rhvgUPZJSGdcE+lvCszKOv9YCZzs7heRUWVG4IV11WxL9SKRB1x/wTKsAOB\n"));
  restServer.sendContent_P(PSTR("    wntgDCAYAocpQLGmkSh9rcPACo2JqN1ALWW3auzonT73aqbssfCzcd9bcOBagZmN7GIdS83cGUxSXqpAEohRAuWEwEQdW8NG0C4HAc/wql9A34JXCEIj5B\n"));
  restServer.sendContent_P(PSTR("    qvmOBnGTBoIIBBtvZj1oAHDklRYMnpP3uimBT/x0dqlzNHlcXnzwVC2fPo51NxYhLlm9VeF1i5gYZpcPUJFK59EgTIsAOJ3HbwfwAiHKNljwYUlfAkHDdm\n"));
  restServer.sendContent_P(PSTR("    moJzxvXnJaPFZdwzrGvJMiDv4hcIZPyDbTWQF1DbtVRR0/e6EJw72sklu4Ph25y1VN2+cZ6ZuQTmtEVLVnUdQFYGDg2NcpxWPhtK036JGayc6Dzs7w3bnF\n"));
  restServer.sendContent_P(PSTR("    F2dKYvQDbSM48de2AHcEh3c2UYqgOYP+dNYMoOEDNoPIaDZg9ddUKe0Mct+NTos6NW1EVQCczmNfIoT8IZJ2CyvZ7K7WI31h626EABtvKpEEkU6+0Yo+Lq\n"));
  restServer.sendContent_P(PSTR("    qnhASL1CKZGAo9RU2OeXDo2QY2jEyADbuLJXkNajh7tJctoKT2pTMd/WraiJoADA6eXEMpeRnBV+WGpGJtNfN5pH8CAwH85UqIT9Fj7Q1sZpUoUnz4ZK3q\n"));
  restServer.sendContent_P(PSTR("    cLFGp5HY3a7R0Ev4Pv5jgyRzuHRLVtgZRMBURjLv6iaE/l1tO1ERgN7ew1miKO4HEFlgHMDKzeuh07MKUd3BrojatK9OlaR9D54bx5G/NKtqhxBAy2Xwus\n"));
  restServer.sendContent_P(PSTR("    aCC0DLZ71o+Zz9pfIx/nBo+qRXshZBpOI+te1ELACUUkGr1T4FIC3StgAgMTkJyy9ay5Q1ftTNb8KgmnU3FEnW4J0+0MWv6g2JllvEESz7eHxwEp/8iU0e\n"));
  restServer.sendContent_P(PSTR("    FQSCTd+UWihq8Li8OLH/LFdKz65p7HhPbVsRC8Dg4MmfA/hSpO34s+2ma5nPVKT4/EV1v1YeQ4IO6/dwuQOU4sOn6zA5rlyT1+rYFyeK8goKpcBHz9RJRo\n"));
  restServer.sendContent_P(PSTR("    jKK3OwJMA6QqXUvN2OMV73oHjoAUB1ClREAuB0nthKKb0/kjbkKKosRdVGNlzQddqBuvcjmwpslRZJaHd0YAKf7WtU3AbvmaQBvvL6g13oqGHnaGtuYtAY\n"));
  restServer.sendContent_P(PSTR("    vxL6modw8k2JFdMe78IT4bQXtgB0dn5mpJT+NpI2gnHT3bdDp2eH7M+eb0TXGVV+Dgmrri1AUiprzjUe6kbbMWXKs9vFvnF+XR8ADPeO4/MX2BFLoxOw6Z\n"));
  restServer.sendContent_P(PSTR("    bSiJJHR/oncOC3pyV+DAryg33t7WF5uMJ+eUaj/qeQ2QEjWmTkZuHa7+xhyrweigO/ORWREGgNGmy8qRSEczEferYeE8OhTTrPBDuk6+K4dX0ixQdP1koU\n"));
  restServer.sendContent_P(PSTR("    NKUx/kAM947jb4+cwPgg10eCl15raFWt/F24PQyGho6WeL3CcURo8nm9Xrz8+J9w4tBhiF55bbqn/RxGh1kzkJApJ0okGTljzkmMc/OoPl4rGR14+ttGmC\n"));
  restServer.sendContent_P(PSTR("    1mklLjmOXd40OTGHOy7eriNEhOYwNJanBPeDHSPyHnwXQB9DRApEoMgQiKjwXN+I9eqe0L6PQISwAcjuPvAAgrDdmft/a+gqcfinh10yLBoPR/9je23xHo\n"));
  restServer.sendContent_P(PSTR("    suopwOk8sRVRePkA0MZl/ywyDRBSHeyyagGglFmuHBGWNGu0mlokAAQkaOBDlSO6v//YegCbI+qRH7YCu6Tshn+9E4b48OfLWGfvo49gYvxCkEgEPR2kuj\n"));
  restServer.sendContent_P(PSTR("    oB0GjIf0SQVCPBli9ddLH+8itQWFEZvYfEEBNjo3jqoV8zZQLFqQDVp64rbXxo6GgJpbgqzL7Jkp5rg1bLetZaG1RFMxfx42x9HSj3C/VSMToC4PUKNyHK\n"));
  restServer.sendContent_P(PSTR("    m0trtRqkZbMp0O2NDQFqLxKKtoZ6vsg1ltvRFOweRQJAKSUAdofZr6DY8lnXaKv0n1hEIW0N7I+HAHUHDiBouFKRADidJzcDmJbNC7M4PUBGihdRSBs3fV\n"));
  restServer.sendContent_P(PSTR("    IEn/8B5SPA18PsU0hsBawAdLWexaQr8uVcsYh09AxuAQAKBYAQdhPmaMKPAKLXi87moNPWIjK4xsfR08mmm1MIkY8ATufxAkxj0CczL0eSCbyoB6inrbEB\n"));
  restServer.sendContent_P(PSTR("    VGQjlUJ0pgByadi9UoDeoEdqFhujb1u0BM5Te/Qw/veBn+CNPz4jecH+8LoTAdxxhqSQv6SQjiBK6bQKADDlEOpuu7Bqh1dmYpW2xgbcv/t6uCenoov958\n"));
  restServer.sendContent_P(PSTR("    5hz13/HqAu+64p0LCvpiZkfFuJDjDte9dnLZqCsnz45uvnXz4AfP5+4DMkpN8ZCTn8AyEEgNJ6A4DwN8BTCO8L6Gpphscd/tLrhUJTTQ3z2ZwaOO9WMgVQ\n"));
  restServer.sendContent_P(PSTR("    GrkAOBxjxZiBc4V4S8Dj8aCrlc96jT2aTrMCULC0Qraee3IS3W1c0E9ASBNwqlqwiwJKlTQSKdkFuSAC25VY1wPGRkbQ3c6+1Pyl5bJ1O5oa4eUyqigJHg\n"));
  restServer.sendContent_P(PSTR("    PwEVQARHFmBEAfZ4A1nV24Eet6QPOZU5LATkEAAZD5rrzxY0TRLyioABBCAu/PFmVsBayqwfu1Y42mU+zwH2dMQEaOfEq5jNncpDRLOJQVMGNn19gK2H8u\n"));
  restServer.sendContent_P(PSTR("    1mMCzWfYKTx/6VLJNOkjnBiAjxACMHOHF2XZ2R2+2psaJPNaLNGsUAEEpFMAiZ4AkBkTgGxuBJDVbGMEr9eD1nr2V51ftlS2rsfjQdfZFqaMgCiyAICQOk\n"));
  restServer.sendContent_P(PSTR("    Dkq32VkpWfC8ItvY7VaaC9sVESEQ00Asj5TMQQaWD+hHAEIYoZgMGJTzDCnMpmCceqJcDb/4JGg9xi+TMhZL4jaowbr1X6rBACQNRvoxEBEkWwMTYFgFcA\n"));
  restServer.sendContent_P(PSTR("    bfkFATOlZfwlLftqehXvqBFiCqAzKwCL2UEAgOZTyhVA3gRU6gL2EcoMjHy/dRVk2vkRQBrjjgWaa6UmYCD4KUBJEog/ocxA9TshRgBvCchluSx0+rvPYb\n"));
  restServer.sendContent_P(PSTR("    CfXaoeaASQzZ4SQqeBMdWDXSQE0hORpxFeBwBiTxFsOi39AeeXybuA5fInCRWjJwCUQrE2GQ0SkhORYmUPa461oBA//1tS02BaIr+RpJyONC4aoicAGs3M\n"));
  restServer.sendContent_P(PSTR("    CgAA2PJjOybQfIYdAfLLlXsAAbT/rUndFuZBBSApyd0EYEYzM2J9nQA/BQSKAAKyq6hUKYBASB1gtZsQKN9BKQpITMHGeklYdKEyMTYqSYQJNP8D0nWUam\n"));
  restServer.sendContent_P(PSTR("    IAPkLmBFJKP1DbaCTwI8DYyAj6z0W2O9h8ofnMGYnZW1AuLwBUFNHRxFoAIlUeA/ChQABI4EzEaYDXAYDYsQT4CKAhPh6ZuXbZut0d7cw+AEDopeByhBQA\n"));
  restServer.sendContent_P(PSTR("    r1erev/ZSEixmpBkYo8YiBU9gFcA7aVLIWjkUzLlvhOt3hv9ESA1tbyLEER+9JYKsuy8HhAblkDfOXY7+UAhYEB2H4VzancKBxQvDsVf1TYcCbxDKFY2ja\n"));
  restServer.sendContent_P(PSTR("    hcu+7834QQXHT1joB1peaxuhiAD0VbxBBCnqWU3hnOA8JBslCkPjYE4JpvfwfxxgScPvw5Nl21DdUbNwWsK50ClC0E4VEkACbTss8cjuMnAczI5j28KTg6\n"));
  restServer.sendContent_P(PSTR("    NISB3h5YgiyMWAgQQrBt983YtvvmoPUopWhvkmwGoXr+B1RsEUMpng3nAeEgFxNoq48NRVAJfV2dGBthA7U0zClAhQDQZwAo31c9AsypVhiT2OPvYkUPUI\n"));
  restServer.sendContent_P(PSTR("    KcWayj7ukVAKu1up0QEvamxGrJ4nIDFjePuoDMd9H/UmN3Tzhtqdop1OsVHkQYhxKEgzQ9bGELwJt7n8Pd1+7CL793G/pCeD4lWUBATYCqIVG1UaTVWnHK\n"));
  restServer.sendContent_P(PSTR("    4Tj+KoAvh/tApfDrBBbyFNBYcxKP/uS+858nJybws98/HbA+/13QMDyAPlTvFUwI/Tkw/dnCfHbQYH8/hhwD0/3YWeHIB/9gPneE2COpnd8OTlAfA/ChWg\n"));
  restServer.sendContent_P(PSTR("    BMpurDAJ4P94FK4X0BwMKNCfAxgCx74B35Bnp7MDzIHpghkhkcAQDA49HeAWBa8wWtGamIM7InbCzUmAC/EDRoFrCMOawh4ZmAQJgCMBUfIA+G+1AlEEKQ\n"));
  restServer.sendContent_P(PSTR("    abcxZQtRACYnJtDJLe0KngUs0YWGXqltC/tY9LDPDEpJ6XsYwLFw71dCLKwTOFtfB9HLulfspYEFQGoCkrAtACACASDkUg+l5GYA4Z/HHoJY2EeYX9cXZ0\n"));
  restServer.sendContent_P(PSTR("    xAdmFhwPrSdQDhD/9AhEe+WSzLjlOKeyNpIxi8IjjQ042RQXUnfc51SquXo3z1mvOfr/vOv0CjCWydS0ZBGl4MwEf4R1d/gcVS9ajTeXwjpYj6fsJyB0q0\n"));
  restServer.sendContent_P(PSTR("    NTZg6cpV0X7UrCFoNPjVM3tx4tBHMFmXwB4kB2DIMYDBATbkL8zmCOBDFCe/CyDqrro0WwZ0BvbwyIW4TkCj0WL5pouDvnxAPizuFXWzLwAWy+pBQshVhO\n"));
  restServer.sendContent_P(PSTR("    Bc6NrKIYKArLzYzA6SQ0YHGnm9ubk1kjajduyrybSsURTJlQAiO9uVI9bXCfgjsQAITiNCr2xUz/21WJYdB4RrAERtw3/+PIGFaAkoJRrrAHiifvCz2Vz5\n"));
  restServer.sendContent_P(PSTR("    LkCvR5TMQ34E6OvqxPjojK5anzPwXsBw1gHwTMvJ32Zz9SuiSC8DoDpLlSeb2z+QUhqTeoAvLc6fOTkC+LBaqw+JorgZiGyJeVp2JnR69pDoWNQDZC2ACE\n"));
  restServer.sendContent_P(PSTR("    1AIMrHwMnhcJzKAzzPA1gdbhv33/A9tDdeWDOXmWdHZu60b2I+pxjo6UELu3PIeHxDW9K+CNP0InYEhcJsLj9L6bsbHA7rLwjBvQhD6NJzshgB6DrbItkb\n"));
  restServer.sendContent_P(PSTR("    L9agQEukLx+YxinAH0Iu9VgsVfcB+CoAh9r7Y2V1sBpIlFLzZkQAfJjNVX+hVLMcwEtq7ssrCRwciVkooqIITfsUwGOxVLQCuMbpPPYlgDxKKcpC3VO1cR\n"));
  restServer.sendContent_P(PSTR("    Ve+h27LEGv1UIQpl2FmRNQAK5JNmpICHkxGm3PuAD4MJmq32lr+3BlYmLiPQDuAmAKVDcrL1tStmPTCuTbFvZKIR+O4VH8/tUDTBkVxKhs3zOjUwBPTs7G\n"));
  restServer.sendContent_P(PSTR("    cbO56udutyYHoHcCkM2HNiYlINmcwpQNDI/ORBfnBI4h6f+qndRGJSo2qwLgIy2tYsRsrn7E5aLFAL2LEGmMOyOPTQ9zDMWON9AhFfbul1taohJzmRMC4C\n"));
  restServer.sendContent_P(PSTR("    Mjo3rUbK5+2GSqKhdFsZJS/BeAbgDIzGWngYGR2BkBBnhhp4haTHxOCYA/VuvyGoul6j6TaTKHEHIFpeIB/+tOmWFxoeIcZreCASFR275v1pRApRCy2g3g\n"));
  restServer.sendContent_P(PSTR("    7Z2FOQkg2OIrHxmbgNvjgU475/+FiOnnRwAiLvwRgEcUBEbqKQAH/8tYgLg9HoyNTzBlhCo7EUwJ80YAjPrERgDMIUJy2vFCwzE0Js34EDRRmwLmjQDsq6\n"));
  restServer.sendContent_P(PSTR("    mZJACzi6JjeOFbAgPS/9Ebp0sIvnhQBfNGAACAcsrPQEyMABIBaFZyKrhS5pUGRSmtJcA23+dz/YOobV3Yu4i29XArokn05n9gngkAwAZAHMMj2H/w8Gz1\n"));
  restServer.sendContent_P(PSTR("    ZVaglEZ1B/d5NQUIVJjx7evnGoREzwkEzDMB0HjJYUQx43g+IkI8FM325pUATPm/6a1AdBegzBOcFOS+1+s7jkaz0f8HLMVNFEf83NgAAAAASUVORK5CYI\n"));
  restServer.sendContent_P(PSTR("    I=' type='image/x-png' />\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("    <!-- Android Meta Tags -->\n"));
  restServer.sendContent_P(PSTR("    <meta name='mobile-web-app-capable' content='yes'>\n"));
  restServer.sendContent_P(PSTR("    <link rel='shortcut icon' sizes='128x128' href='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAA\n"));
  restServer.sendContent_P(PSTR("    BHNCSVQICAgIfAhkiAAAAA\n"));
  restServer.sendContent_P(PSTR("    lwSFlzAAADgAAAA4AB/Pg+8wAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAABqpSURBVHic7Z15dBzFnce/1XNJo2sO6xwdo1uWZMn3\n"));
  restServer.sendContent_P(PSTR("    CdgQzOErCQSWYANJCEuS3SwQFgI5dklI8rLv8d7CPh67SSB5nIljroCBACEYYsBcvmVbt6zTOmd0azQzXfuHGHuqumeme2Z0jj5/aaqrq0vTv6n6XVVFsE\n"));
  restServer.sendContent_P(PSTR("    hQLi8oSDEQ97cJodcApBiAAUADKHmHUM+jrzZ1ts52HyOBzHYH5jLbi3KuJMBzACxy1wngFkHufa2h9eEZ7lrU0Mx2B+YqO4qydxOQfQASglTTEOCqYktK\n"));
  restServer.sendContent_P(PSTR("    Sv3A0Jsz1bdosigAMuwqzC6iRHgVQJyS+gTYUGxOqa13DJ2c5q5FnUUBkKHYmvIigBL/MnNOApbvsCNvRSqoSDHUM87cQwi2lKXq/6+2f2xyJvsaKYsCwL\n"));
  restServer.sendContent_P(PSTR("    GzMO8yEPof/mW2CjO23lGFJfYkmLMTkL8mDaJHRE/jkH81I6X64bqBwYMz2+PIEGa7AzPB9txc8xa7XdFwTgXxZ/6ftXoN1t9UAkHD6svLd9phyuLVA3r3\n"));
  restServer.sendContent_P(PSTR("    rtIlSaGesWULtNtzc81btkCrpE/TyYK1AnaVZpWKXu3dAL0aQPYXxR0A3hQgPPpKw9kjknuKc7eKlL7lX1a+NRurvpov+4yzh/vw/uOnmTIK/Pi1hrZf8X\n"));
  restServer.sendContent_P(PSTR("    V3lGTbIJIfALgawNIvip0EeJuK5Df7m1rfUfs/RoMFKQA7C3N+TAl+iimbXQ6REPp4nN51976a3pHz9xXlvEeBS3yftXoNvvrgasQl6eVboRT7f3UEjo5R\n"));
  restServer.sendContent_P(PSTR("    /9IBMubNebWzc+yLz2R7Ue69BPSnCGJREJBnhj3CbQdaWiaU/ZfRYcFNAduLcn5ECX6BwC8fAARKyT9PuOI+3Fmalw8AO0ps1f4vHwBKN2cFfvkAQAiWbc\n"));
  restServer.sendContent_P(PSTR("    vlSy0wCjcCwHUVqYk7C3OeJ6C/RnBzEhR0T6LWu3emp4UFpQTuLMhZA4I/QvnIlg5KbyyypnwsALcCZJXvgiAQXHxbGXSG4F9RSoYRzZ/0YHLM41cq5Jan\n"));
  restServer.sendContent_P(PSTR("    md+c9GjeBrBFxb9QahhK6a4bGPpUxT0RsaAEoMSa8jiAYv8y+6pUrNhlR8G6NAhaAc7OMYAytyUIwB6ALAOg8xXaqqwo2ZQR8pmEAG6XF+dqB/2LM0SR3g\n"));
  restServer.sendContent_P(PSTR("    LAztfPKDNhxZftKLk4E3FJevSfHQZl+7M8K9nyWIvT6eHvnQ5mXQuNFrtKlySJXlzhX1a0KQMbdl+QB1ulBYXr0vDe42fgGnGfL6dTL17nf2/xxtAv30fh\n"));
  restServer.sendContent_P(PSTR("    +nQc298KKjJv0uz/QdAQrLmuECWXZJ4vyywzITktDoeea/CvakvQuDcAeFdxByJgwegA1JOwBtyItuwqyfyM9BITrr53uYwJdwFjsh5ZFeaA1yX1TQZklQ\n"));
  restServer.sendContent_P(PSTR("    eub0jU4fLvVzIv30fRxgwYkzk9gwgbFD88QhaMAIB4C/w/GhJ0SLTK64FJS+Jw1T1VyF4mG+NBcqYRgqDOQLLmyZv/KZlGbPvhcqSXmGSvE4HAnJvIloHI\n"));
  restServer.sendContent_P(PSTR("    253TwMIRABDmDeiNwdUbnUGLzbeXI2/lEsm17jonGj/qVvzk/pZhnHq7XVJutiXiyruqkGgN7oPSx/MzMQ3pTIoW804H+EqZ3e7xeG4BEZxk1PM7n71NQZ\n"));
  restServer.sendContent_P(PSTR("    P9lX9tXGj9VhAILv5WGQRNHZo/7TlfTilw6Ll6JFgNyAjwy/UxPjiJ9357Gp5JL1NutiVi6x2VMCTqAtx5AZ2B/R0SSv2HBLJ9KjJZLhL6l9fr2z8O2aAK\n"));
  restServer.sendContent_P(PSTR("    5tUIsL0o9zqPx3sMIA+A0odh1LyAL9464UcAgzLZJgLBxltKkLeKHQlEL8X7j5/BcF9gv4xn0ou/P1aDUaeLKVfz8gFAy40AFCTZ9/f2otwHCMjTAO4XKP\n"));
  restServer.sendContent_P(PSTR("    lwR1H2fz4Qxfc2bwRgR3HOTwjonwGc/3IocNXO4tzvAwAIO2wqGQF8CALBRd8sQ3Ylq8i5Rtw4+MQZiF4qe9/nzzdhoG2EKUtOi1f18gFAp+deA5kaAbYX\n"));
  restServer.sendContent_P(PSTR("    5m0koD/27ypAHvisKHvvdRUVQTxUypkXArCzKOeXoHhQ7hql9Nc7S+xlfLnoEVU9QxAILrq1DKZs1jroOzuMY/tbJPVbj/ah7uA5pkwXp8Hm28tVvXwAMg\n"));
  restServer.sendContent_P(PSTR("    JG6BVV6QmEiE9C1ldDvjbuGnp51apV6h4kw5wXgB2F2bdR4EdBqsRT0fusCA0zCXsm1QkAMKUYXnp7OfRGdkg++VYHev1CvxMjbhx6toG9mRBc8u2lMGUa\n"));
  restServer.sendContent_P(PSTR("    VT/X4/JKivSj+ocAFAW57erMwZ7fqH4Yx5wWgJ1FtvUg5DG+PE76C1tJqHe5f4HMl6qIRGsc1t9YzBZSikN7GyB+4eg5/GIzXKNupkrF5dlBfQHBcPPCSm\n"));
  restServer.sendContent_P(PSTR("    EEwe3+RYYE3ZTbkeWb24tyvhvWQ79gzgrAzqwsIyA8A85SKVifhu33r5D8SgnIOv+BNFwBAIC8lUtQtIH1BDrbR3Hm3U70NA6i6WPWRLTkJGL5rrywnyfp\n"));
  restServer.sendContent_P(PSTR("    K0ER/EwaQoCLby3D2usLwEOAh7YV2EokFxQyZwVANGp/SIFC/7LsZRZs2FMCo9mAtf/EXAIFGNeNeyJ8AQCAldfmIy6JHWlOvNGKT59vZnz3RCBYv7tYkj\n"));
  restServer.sendContent_P(PSTR("    CiBpm+Mo6D0i1ZyCwzoXRzFqq2SwTNKAhC2FnJc1IAduXnpxPQe/zL4pJ12HhL6XkPXf6aNFknjg/XqBveMPQAHwajFiu5RJDJMQ8Gzg4zZaWXZMLKefLU\n"));
  restServer.sendContent_P(PSTR("    MuYInEaYnGbEii/bz3+u2paLtKJkvtrVOwvzLgvn2XNSAAQDuQNAvH/Zmq8VwsAN++tvLEaCSd7dSykw0h9ZbkXBunSYbYFfrtagQdV2abxBLcN947Llgk\n"));
  restServer.sendContent_P(PSTR("    Cw6Rsl0OovGAKEABv2FEOj5UYcIt6DMJhTAtDXd9TW23Pkv41Jxh/6l6cWJMO+OlVSX2/UYu2NxTK60RSD3WPyFxRCCFC1PSfg9bLNmVPKWQSMOV0B9ZXK\n"));
  restServer.sendContent_P(PSTR("    K3OwxC71CienGVF8ERtYosCVvuQWNcwJAXA4jtgdjmOPaDRC/ZkjJ+4ccgwy/ZKLovnIrjSjOEDcnnfShENO9RLZyKFGL2Dp5dkyd6ijv1W+j+acBLlso/\n"));
  restServer.sendContent_P(PSTR("    OUbM7iBZ+IXnq92ufPqgAMDx9LcziOPwFo6gHybwDiT3z0OVPHkKBD3orAcz0ArLq2AElLpAGXjhOOiPtICGQFLKPEJGeOqqbzlFNSptEJuPgbZUEVy5T0\n"));
  restServer.sendContent_P(PSTR("    eKQVpbB9nUqAVcWsCAClVHA4jt3s8Qg1AL4FP1Ov9ugppm5mmQkaXfBuag0abLy5VGInD3SMYMzhCnCXcvLXpUn6EOnQDwBUpGj+RBp1XL7LjhQFDqXsSk\n"));
  restServer.sendContent_P(PSTR("    k4e61aF/GMC4DTeWyl03niY4A8CVDmp00pRXtDC1PfKjMHypFWlIwKfkimwPtPnImov8CURWCrYL/swa7RALWVc/y1VokJmFaUjPLLshTdb82XfDfxE67h\n"));
  restServer.sendContent_P(PSTR("    Yrm6gZgxAaCUEofj2B2Uko8ArJarM9jvgGuC1dzVmFjVO/NgtrHzdW/TEBoPKY/tB8LGZQgNtI1gfNAdoHZonO2jOPlWG1Omi9Pgom+UyXn8ZLHmJkrqUk\n"));
  restServer.sendContent_P(PSTR("    DqLQrCjAhAf399stN5Yi9AHgYQcIgackjnw6Bp2Rwa7ZTZxM+dn/65ESP9kU0FtkoL811TCvQ0DQa+IQheD8U/nqqVBIHWXFeIBEuwbHYWrV4DLT89Ehpc\n"));
  restServer.sendContent_P(PSTR("    YeKYdgFwOI6uEISx4wCuC1XX7ZI6RDQ6dR42sy0R1TtYb5l7wouPnq4Dn36rhvgUPZJSGdcE+lvCszKOv9YCZzs7heRUWVG4IV11WxL9SKRB1x/wTKsAOB\n"));
  restServer.sendContent_P(PSTR("    wntgDCAYAocpQLGmkSh9rcPACo2JqN1ALWW3auzonT73aqbssfCzcd9bcOBagZmN7GIdS83cGUxSXqpAEohRAuWEwEQdW8NG0C4HAc/wql9A34JXCEIj5B\n"));
  restServer.sendContent_P(PSTR("    qvmOBnGTBoIIBBtvZj1oAHDklRYMnpP3uimBT/x0dqlzNHlcXnzwVC2fPo51NxYhLlm9VeF1i5gYZpcPUJFK59EgTIsAOJ3HbwfwAiHKNljwYUlfAkHDdm\n"));
  restServer.sendContent_P(PSTR("    moJzxvXnJaPFZdwzrGvJMiDv4hcIZPyDbTWQF1DbtVRR0/e6EJw72sklu4Ph25y1VN2+cZ6ZuQTmtEVLVnUdQFYGDg2NcpxWPhtK036JGayc6Dzs7w3bnF\n"));
  restServer.sendContent_P(PSTR("    F2dKYvQDbSM48de2AHcEh3c2UYqgOYP+dNYMoOEDNoPIaDZg9ddUKe0Mct+NTos6NW1EVQCczmNfIoT8IZJ2CyvZ7K7WI31h626EABtvKpEEkU6+0Yo+Lq\n"));
  restServer.sendContent_P(PSTR("    qnhASL1CKZGAo9RU2OeXDo2QY2jEyADbuLJXkNajh7tJctoKT2pTMd/WraiJoADA6eXEMpeRnBV+WGpGJtNfN5pH8CAwH85UqIT9Fj7Q1sZpUoUnz4ZK3q\n"));
  restServer.sendContent_P(PSTR("    cLFGp5HY3a7R0Ev4Pv5jgyRzuHRLVtgZRMBURjLv6iaE/l1tO1ERgN7ew1miKO4HEFlgHMDKzeuh07MKUd3BrojatK9OlaR9D54bx5G/NKtqhxBAy2Xwus\n"));
  restServer.sendContent_P(PSTR("    aCC0DLZ71o+Zz9pfIx/nBo+qRXshZBpOI+te1ELACUUkGr1T4FIC3StgAgMTkJyy9ay5Q1ftTNb8KgmnU3FEnW4J0+0MWv6g2JllvEESz7eHxwEp/8iU0e\n"));
  restServer.sendContent_P(PSTR("    FQSCTd+UWihq8Li8OLH/LFdKz65p7HhPbVsRC8Dg4MmfA/hSpO34s+2ma5nPVKT4/EV1v1YeQ4IO6/dwuQOU4sOn6zA5rlyT1+rYFyeK8goKpcBHz9RJRo\n"));
  restServer.sendContent_P(PSTR("    jKK3OwJMA6QqXUvN2OMV73oHjoAUB1ClREAuB0nthKKb0/kjbkKKosRdVGNlzQddqBuvcjmwpslRZJaHd0YAKf7WtU3AbvmaQBvvL6g13oqGHnaGtuYtAY\n"));
  restServer.sendContent_P(PSTR("    vxL6modw8k2JFdMe78IT4bQXtgB0dn5mpJT+NpI2gnHT3bdDp2eH7M+eb0TXGVV+Dgmrri1AUiprzjUe6kbbMWXKs9vFvnF+XR8ADPeO4/MX2BFLoxOw6Z\n"));
  restServer.sendContent_P(PSTR("    bSiJJHR/oncOC3pyV+DAryg33t7WF5uMJ+eUaj/qeQ2QEjWmTkZuHa7+xhyrweigO/ORWREGgNGmy8qRSEczEferYeE8OhTTrPBDuk6+K4dX0ixQdP1koU\n"));
  restServer.sendContent_P(PSTR("    NKUx/kAM947jb4+cwPgg10eCl15raFWt/F24PQyGho6WeL3CcURo8nm9Xrz8+J9w4tBhiF55bbqn/RxGh1kzkJApJ0okGTljzkmMc/OoPl4rGR14+ttGmC\n"));
  restServer.sendContent_P(PSTR("    1mklLjmOXd40OTGHOy7eriNEhOYwNJanBPeDHSPyHnwXQB9DRApEoMgQiKjwXN+I9eqe0L6PQISwAcjuPvAAgrDdmft/a+gqcfinh10yLBoPR/9je23xHo\n"));
  restServer.sendContent_P(PSTR("    suopwOk8sRVRePkA0MZl/ywyDRBSHeyyagGglFmuHBGWNGu0mlokAAQkaOBDlSO6v//YegCbI+qRH7YCu6Tshn+9E4b48OfLWGfvo49gYvxCkEgEPR2kuj\n"));
  restServer.sendContent_P(PSTR("    oB0GjIf0SQVCPBli9ddLH+8itQWFEZvYfEEBNjo3jqoV8zZQLFqQDVp64rbXxo6GgJpbgqzL7Jkp5rg1bLetZaG1RFMxfx42x9HSj3C/VSMToC4PUKNyHK\n"));
  restServer.sendContent_P(PSTR("    m0trtRqkZbMp0O2NDQFqLxKKtoZ6vsg1ltvRFOweRQJAKSUAdofZr6DY8lnXaKv0n1hEIW0N7I+HAHUHDiBouFKRADidJzcDmJbNC7M4PUBGihdRSBs3fV\n"));
  restServer.sendContent_P(PSTR("    IEn/8B5SPA18PsU0hsBawAdLWexaQr8uVcsYh09AxuAQAKBYAQdhPmaMKPAKLXi87moNPWIjK4xsfR08mmm1MIkY8ATufxAkxj0CczL0eSCbyoB6inrbEB\n"));
  restServer.sendContent_P(PSTR("    VGQjlUJ0pgByadi9UoDeoEdqFhujb1u0BM5Te/Qw/veBn+CNPz4jecH+8LoTAdxxhqSQv6SQjiBK6bQKADDlEOpuu7Bqh1dmYpW2xgbcv/t6uCenoov958\n"));
  restServer.sendContent_P(PSTR("    5hz13/HqAu+64p0LCvpiZkfFuJDjDte9dnLZqCsnz45uvnXz4AfP5+4DMkpN8ZCTn8AyEEgNJ6A4DwN8BTCO8L6Gpphscd/tLrhUJTTQ3z2ZwaOO9WMgVQ\n"));
  restServer.sendContent_P(PSTR("    GrkAOBxjxZiBc4V4S8Dj8aCrlc96jT2aTrMCULC0Qraee3IS3W1c0E9ASBNwqlqwiwJKlTQSKdkFuSAC25VY1wPGRkbQ3c6+1Pyl5bJ1O5oa4eUyqigJHg\n"));
  restServer.sendContent_P(PSTR("    PwEVQARHFmBEAfZ4A1nV24Eet6QPOZU5LATkEAAZD5rrzxY0TRLyioABBCAu/PFmVsBayqwfu1Y42mU+zwH2dMQEaOfEq5jNncpDRLOJQVMGNn19gK2H8u\n"));
  restServer.sendContent_P(PSTR("    1mMCzWfYKTx/6VLJNOkjnBiAjxACMHOHF2XZ2R2+2psaJPNaLNGsUAEEpFMAiZ4AkBkTgGxuBJDVbGMEr9eD1nr2V51ftlS2rsfjQdfZFqaMgCiyAICQOk\n"));
  restServer.sendContent_P(PSTR("    Dkq32VkpWfC8ItvY7VaaC9sVESEQ00Asj5TMQQaWD+hHAEIYoZgMGJTzDCnMpmCceqJcDb/4JGg9xi+TMhZL4jaowbr1X6rBACQNRvoxEBEkWwMTYFgFcA\n"));
  restServer.sendContent_P(PSTR("    bfkFATOlZfwlLftqehXvqBFiCqAzKwCL2UEAgOZTyhVA3gRU6gL2EcoMjHy/dRVk2vkRQBrjjgWaa6UmYCD4KUBJEog/ocxA9TshRgBvCchluSx0+rvPYb\n"));
  restServer.sendContent_P(PSTR("    CfXaoeaASQzZ4SQqeBMdWDXSQE0hORpxFeBwBiTxFsOi39AeeXybuA5fInCRWjJwCUQrE2GQ0SkhORYmUPa461oBA//1tS02BaIr+RpJyONC4aoicAGs3M\n"));
  restServer.sendContent_P(PSTR("    CgAA2PJjOybQfIYdAfLLlXsAAbT/rUndFuZBBSApyd0EYEYzM2J9nQA/BQSKAAKyq6hUKYBASB1gtZsQKN9BKQpITMHGeklYdKEyMTYqSYQJNP8D0nWUam\n"));
  restServer.sendContent_P(PSTR("    IAPkLmBFJKP1DbaCTwI8DYyAj6z0W2O9h8ofnMGYnZW1AuLwBUFNHRxFoAIlUeA/ChQABI4EzEaYDXAYDYsQT4CKAhPh6ZuXbZut0d7cw+AEDopeByhBQA\n"));
  restServer.sendContent_P(PSTR("    r1erev/ZSEixmpBkYo8YiBU9gFcA7aVLIWjkUzLlvhOt3hv9ESA1tbyLEER+9JYKsuy8HhAblkDfOXY7+UAhYEB2H4VzancKBxQvDsVf1TYcCbxDKFY2ja\n"));
  restServer.sendContent_P(PSTR("    hcu+7834QQXHT1joB1peaxuhiAD0VbxBBCnqWU3hnOA8JBslCkPjYE4JpvfwfxxgScPvw5Nl21DdUbNwWsK50ClC0E4VEkACbTss8cjuMnAczI5j28KTg6\n"));
  restServer.sendContent_P(PSTR("    NISB3h5YgiyMWAgQQrBt983YtvvmoPUopWhvkmwGoXr+B1RsEUMpng3nAeEgFxNoq48NRVAJfV2dGBthA7U0zClAhQDQZwAo31c9AsypVhiT2OPvYkUPUI\n"));
  restServer.sendContent_P(PSTR("    KcWayj7ukVAKu1up0QEvamxGrJ4nIDFjePuoDMd9H/UmN3Tzhtqdop1OsVHkQYhxKEgzQ9bGELwJt7n8Pd1+7CL793G/pCeD4lWUBATYCqIVG1UaTVWnHK\n"));
  restServer.sendContent_P(PSTR("    4Tj+KoAvh/tApfDrBBbyFNBYcxKP/uS+858nJybws98/HbA+/13QMDyAPlTvFUwI/Tkw/dnCfHbQYH8/hhwD0/3YWeHIB/9gPneE2COpnd8OTlAfA/ChWg\n"));
  restServer.sendContent_P(PSTR("    BMpurDAJ4P94FK4X0BwMKNCfAxgCx74B35Bnp7MDzIHpghkhkcAQDA49HeAWBa8wWtGamIM7InbCzUmAC/EDRoFrCMOawh4ZmAQJgCMBUfIA+G+1AlEEKQ\n"));
  restServer.sendContent_P(PSTR("    abcxZQtRACYnJtDJLe0KngUs0YWGXqltC/tY9LDPDEpJ6XsYwLFw71dCLKwTOFtfB9HLulfspYEFQGoCkrAtACACASDkUg+l5GYA4Z/HHoJY2EeYX9cXZ0\n"));
  restServer.sendContent_P(PSTR("    xAdmFhwPrSdQDhD/9AhEe+WSzLjlOKeyNpIxi8IjjQ042RQXUnfc51SquXo3z1mvOfr/vOv0CjCWydS0ZBGl4MwEf4R1d/gcVS9ajTeXwjpYj6fsJyB0q0\n"));
  restServer.sendContent_P(PSTR("    NTZg6cpV0X7UrCFoNPjVM3tx4tBHMFmXwB4kB2DIMYDBATbkL8zmCOBDFCe/CyDqrro0WwZ0BvbwyIW4TkCj0WL5pouDvnxAPizuFXWzLwAWy+pBQshVhO\n"));
  restServer.sendContent_P(PSTR("    Bc6NrKIYKArLzYzA6SQ0YHGnm9ubk1kjajduyrybSsURTJlQAiO9uVI9bXCfgjsQAITiNCr2xUz/21WJYdB4RrAERtw3/+PIGFaAkoJRrrAHiifvCz2Vz5\n"));
  restServer.sendContent_P(PSTR("    LkCvR5TMQ34E6OvqxPjojK5anzPwXsBw1gHwTMvJ32Zz9SuiSC8DoDpLlSeb2z+QUhqTeoAvLc6fOTkC+LBaqw+JorgZiGyJeVp2JnR69pDoWNQDZC2ACE\n"));
  restServer.sendContent_P(PSTR("    1AIMrHwMnhcJzKAzzPA1gdbhv33/A9tDdeWDOXmWdHZu60b2I+pxjo6UELu3PIeHxDW9K+CNP0InYEhcJsLj9L6bsbHA7rLwjBvQhD6NJzshgB6DrbItkb\n"));
  restServer.sendContent_P(PSTR("    L9agQEukLx+YxinAH0Iu9VgsVfcB+CoAh9r7Y2V1sBpIlFLzZkQAfJjNVX+hVLMcwEtq7ssrCRwciVkooqIITfsUwGOxVLQCuMbpPPYlgDxKKcpC3VO1cR\n"));
  restServer.sendContent_P(PSTR("    Ve+h27LEGv1UIQpl2FmRNQAK5JNmpICHkxGm3PuAD4MJmq32lr+3BlYmLiPQDuAmAKVDcrL1tStmPTCuTbFvZKIR+O4VH8/tUDTBkVxKhs3zOjUwBPTs7G\n"));
  restServer.sendContent_P(PSTR("    cbO56udutyYHoHcCkM2HNiYlINmcwpQNDI/ORBfnBI4h6f+qndRGJSo2qwLgIy2tYsRsrn7E5aLFAL2LEGmMOyOPTQ9zDMWON9AhFfbul1taohJzmRMC4C\n"));
  restServer.sendContent_P(PSTR("    Mjo3rUbK5+2GSqKhdFsZJS/BeAbgDIzGWngYGR2BkBBnhhp4haTHxOCYA/VuvyGoul6j6TaTKHEHIFpeIB/+tOmWFxoeIcZreCASFR275v1pRApRCy2g3g\n"));
  restServer.sendContent_P(PSTR("    7Z2FOQkg2OIrHxmbgNvjgU475/+FiOnnRwAiLvwRgEcUBEbqKQAH/8tYgLg9HoyNTzBlhCo7EUwJ80YAjPrERgDMIUJy2vFCwzE0Js34EDRRmwLmjQDsq6\n"));
  restServer.sendContent_P(PSTR("    mZJACzi6JjeOFbAgPS/9Ebp0sIvnhQBfNGAACAcsrPQEyMABIBaFZyKrhS5pUGRSmtJcA23+dz/YOobV3Yu4i29XArokn05n9gngkAwAZAHMMj2H/w8Gz1\n"));
  restServer.sendContent_P(PSTR("    ZVaglEZ1B/d5NQUIVJjx7evnGoREzwkEzDMB0HjJYUQx43g+IkI8FM325pUATPm/6a1AdBegzBOcFOS+1+s7jkaz0f8HLMVNFEf83NgAAAAASUVORK5CYI\n"));
  restServer.sendContent_P(PSTR("    I=' type='image/x-png' />\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("    <!-- jQuery  -->\n"));
  restServer.sendContent_P(PSTR("    <script src='https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js'></script>\n"));
  restServer.sendContent_P(PSTR("    <script src='https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js'></script>\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("    <!-- Bootstrap -->\n"));
  restServer.sendContent_P(PSTR("    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css'>\n"));
  restServer.sendContent_P(PSTR("    <script src='https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js'></script>\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("    <!-- Colour Picker -->\n"));
  restServer.sendContent_P(PSTR("    <script type='text/javascript'\n"));
  restServer.sendContent_P(PSTR("        src='https://cdnjs.cloudflare.com/ajax/libs/tinyColorPicker/1.1.1/jqColorPicker.min.js'></script>\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("    <!-- Chart.js -->\n"));
  restServer.sendContent_P(PSTR("    <script type='text/css' src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css'></script>\n"));
  restServer.sendContent_P(PSTR("    <script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js'></script>\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("    <!-- Cover Template CSS -->\n"));
  restServer.sendContent_P(PSTR("    <style>\n"));
  restServer.sendContent_P(PSTR("        a,\n"));
  restServer.sendContent_P(PSTR("        a:focus,\n"));
  restServer.sendContent_P(PSTR("        a:hover {\n"));
  restServer.sendContent_P(PSTR("            color: #fff;\n"));
  restServer.sendContent_P(PSTR("        }\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("        .btn-secondary,\n"));
  restServer.sendContent_P(PSTR("        .btn-secondary:hover,\n"));
  restServer.sendContent_P(PSTR("        .btn-secondary:focus {\n"));
  restServer.sendContent_P(PSTR("            color: #333;\n"));
  restServer.sendContent_P(PSTR("            text-shadow: none;\n"));
  restServer.sendContent_P(PSTR("            /* Prevent inheritance from `body` */\n"));
  restServer.sendContent_P(PSTR("            background-color: #fff;\n"));
  restServer.sendContent_P(PSTR("            border: .05rem solid #fff;\n"));
  restServer.sendContent_P(PSTR("        }\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("        html,\n"));
  restServer.sendContent_P(PSTR("        body {\n"));
  restServer.sendContent_P(PSTR("            height: 100%;\n"));
  restServer.sendContent_P(PSTR("            background-color: #333;\n"));
  restServer.sendContent_P(PSTR("            overflow: auto;\n"));
  restServer.sendContent_P(PSTR("        }\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("        body {\n"));
  restServer.sendContent_P(PSTR("            display: -ms-flexbox;\n"));
  restServer.sendContent_P(PSTR("            display: flex;\n"));
  restServer.sendContent_P(PSTR("            color: #fff;\n"));
  restServer.sendContent_P(PSTR("            /* text-shadow: 0 .05rem .1rem rgba(0, 0, 0, .5); */\n"));
  restServer.sendContent_P(PSTR("            box-shadow: inset 0 0 5rem rgba(0, 0, 0, .5);\n"));
  restServer.sendContent_P(PSTR("        }\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("        .card {\n"));
  restServer.sendContent_P(PSTR("            background-color: #FFF;\n"));
  restServer.sendContent_P(PSTR("            color: #000;\n"));
  restServer.sendContent_P(PSTR("        }\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("        .cover-container {\n"));
  restServer.sendContent_P(PSTR("            max-width: 80em;\n"));
  restServer.sendContent_P(PSTR("        }\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("        .masthead {\n"));
  restServer.sendContent_P(PSTR("            margin-bottom: 2rem;\n"));
  restServer.sendContent_P(PSTR("        }\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("        .masthead-brand {\n"));
  restServer.sendContent_P(PSTR("            margin-bottom: 0;\n"));
  restServer.sendContent_P(PSTR("        }\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("        .nav-masthead .nav-link {\n"));
  restServer.sendContent_P(PSTR("            padding: .25rem 0;\n"));
  restServer.sendContent_P(PSTR("            font-weight: 700;\n"));
  restServer.sendContent_P(PSTR("            color: rgba(255, 255, 255, .5);\n"));
  restServer.sendContent_P(PSTR("            background-color: transparent;\n"));
  restServer.sendContent_P(PSTR("            border-bottom: .25rem solid transparent;\n"));
  restServer.sendContent_P(PSTR("        }\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("        .nav-masthead .nav-link:hover,\n"));
  restServer.sendContent_P(PSTR("        .nav-masthead .nav-link:focus {\n"));
  restServer.sendContent_P(PSTR("            border-bottom-color: rgba(255, 255, 255, .25);\n"));
  restServer.sendContent_P(PSTR("        }\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("        .nav-masthead .nav-link+.nav-link {\n"));
  restServer.sendContent_P(PSTR("            margin-left: 1rem;\n"));
  restServer.sendContent_P(PSTR("        }\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("        .nav-masthead .active {\n"));
  restServer.sendContent_P(PSTR("            color: #fff;\n"));
  restServer.sendContent_P(PSTR("            border-bottom-color: #fff;\n"));
  restServer.sendContent_P(PSTR("        }\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("        @media (min-width: 48em) {\n"));
  restServer.sendContent_P(PSTR("            .masthead-brand {\n"));
  restServer.sendContent_P(PSTR("                float: left;\n"));
  restServer.sendContent_P(PSTR("            }\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("            .nav-masthead {\n"));
  restServer.sendContent_P(PSTR("                float: right;\n"));
  restServer.sendContent_P(PSTR("            }\n"));
  restServer.sendContent_P(PSTR("        }\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("        .cover {\n"));
  restServer.sendContent_P(PSTR("            padding: 0 1.5rem;\n"));
  restServer.sendContent_P(PSTR("        }\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("        .cover .btn-lg {\n"));
  restServer.sendContent_P(PSTR("            padding: .75rem 1.25rem;\n"));
  restServer.sendContent_P(PSTR("            font-weight: 700;\n"));
  restServer.sendContent_P(PSTR("        }\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("        .mastfoot {\n"));
  restServer.sendContent_P(PSTR("            color: rgba(255, 255, 255, .5);\n"));
  restServer.sendContent_P(PSTR("        }\n"));
  restServer.sendContent_P(PSTR("    </style>\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("    <!-- Websockets -->\n"));
  restServer.sendContent_P(PSTR("    <script>\n"));
  restServer.sendContent_P(PSTR("        var websock;\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("        function onStart() {\n"));
  restServer.sendContent_P(PSTR("            $('#currentModeLabel').html('WS Connecting...')\n"));
  restServer.sendContent_P(PSTR("            websock = new WebSocket('ws://' + window.location.hostname + ':81/');\n"));
  restServer.sendContent_P(PSTR("            websock.onopen = function (evt) {\n"));
  restServer.sendContent_P(PSTR("                console.log('websock opened');\n"));
  restServer.sendContent_P(PSTR("                $('#wsState').html('Open')\n"));
  restServer.sendContent_P(PSTR("            }\n"));
  restServer.sendContent_P(PSTR("            websock.onclose = function (evt) {\n"));
  restServer.sendContent_P(PSTR("                console.log('websock closed');\n"));
  restServer.sendContent_P(PSTR("                $('#wsState').html('Closed')\n"));
  restServer.sendContent_P(PSTR("                // Maybe set up a timer to keep trying to reconnect till window closed\n"));
  restServer.sendContent_P(PSTR("            }\n"));
  restServer.sendContent_P(PSTR("            websock.onerror = function (evt) {\n"));
  restServer.sendContent_P(PSTR("                console.log(evt);\n"));
  restServer.sendContent_P(PSTR("            }\n"));
  restServer.sendContent_P(PSTR("            websock.onmessage = function (evt) {\n"));
  restServer.sendContent_P(PSTR("                // console.log('Incoming Data is: ' + evt.data)\n"));
  restServer.sendContent_P(PSTR("                routeMessage(evt.data)\n"));
  restServer.sendContent_P(PSTR("            }\n"));
  restServer.sendContent_P(PSTR("        }\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("        function routeMessage(jsonString) {\n"));
  restServer.sendContent_P(PSTR("            let jsonMessage = JSON.parse(jsonString);\n"));
  restServer.sendContent_P(PSTR("            // console.log(jsonMessage)\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("            if ('State' in jsonMessage) {\n"));
  restServer.sendContent_P(PSTR("                // console.log('Found State Message')\n"));
  restServer.sendContent_P(PSTR("                handleStateMessage(jsonMessage.State)\n"));
  restServer.sendContent_P(PSTR("            }\n"));
  restServer.sendContent_P(PSTR("            if ('Colour' in jsonMessage) {\n"));
  restServer.sendContent_P(PSTR("                // console.log('Found Mode Message')\n"));
  restServer.sendContent_P(PSTR("                handleColourMessage(jsonMessage.Colour)\n"));
  restServer.sendContent_P(PSTR("            }\n"));
  restServer.sendContent_P(PSTR("            if ('Temperature' in jsonMessage) {\n"));
  restServer.sendContent_P(PSTR("                // console.log('Found Mode Message')\n"));
  restServer.sendContent_P(PSTR("                handleTemperatureMessage(jsonMessage.Temperature)\n"));
  restServer.sendContent_P(PSTR("            }\n"));
  restServer.sendContent_P(PSTR("            if ('Humidity' in jsonMessage) {\n"));
  restServer.sendContent_P(PSTR("                // console.log('Found Mode Message')\n"));
  restServer.sendContent_P(PSTR("                handleHumidityMessage(jsonMessage.Humidity)\n"));
  restServer.sendContent_P(PSTR("            }\n"));
  restServer.sendContent_P(PSTR("            if ('Moisture' in jsonMessage) {\n"));
  restServer.sendContent_P(PSTR("                // console.log('Found Mode Message')\n"));
  restServer.sendContent_P(PSTR("                handleMoistureMessage(jsonMessage.Moisture)\n"));
  restServer.sendContent_P(PSTR("            }\n"));
  restServer.sendContent_P(PSTR("        }\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("        function handleStateMessage(jsonMessage) {\n"));
  restServer.sendContent_P(PSTR("            // console.log(jsonMessage)\n"));
  restServer.sendContent_P(PSTR("            if (typeof jsonMessage === 'boolean') {\n"));
  restServer.sendContent_P(PSTR("                if (jsonMessage) {\n"));
  restServer.sendContent_P(PSTR("                    $('#stateButton').val('ON')\n"));
  restServer.sendContent_P(PSTR("                    $('#stateLabel').html('Turn Off LED')\n"));
  restServer.sendContent_P(PSTR("                } else {\n"));
  restServer.sendContent_P(PSTR("                    $('#stateButton').val('OFF')\n"));
  restServer.sendContent_P(PSTR("                    $('#stateLabel').html('Turn On LED')\n"));
  restServer.sendContent_P(PSTR("                }\n"));
  restServer.sendContent_P(PSTR("            }\n"));
  restServer.sendContent_P(PSTR("        }\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("        function handleColourMessage(jsonMessage) {\n"));
  restServer.sendContent_P(PSTR("            if (typeof jsonMessage === 'object') {\n"));
  restServer.sendContent_P(PSTR("                var newRed = 0\n"));
  restServer.sendContent_P(PSTR("                var newGreen = 0\n"));
  restServer.sendContent_P(PSTR("                var newBlue = 0\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("                if (('Red' in jsonMessage)) {\n"));
  restServer.sendContent_P(PSTR("                    if (typeof jsonMessage.Red === 'number') {\n"));
  restServer.sendContent_P(PSTR("                        newRed = jsonMessage.Red\n"));
  restServer.sendContent_P(PSTR("                    }\n"));
  restServer.sendContent_P(PSTR("                }\n"));
  restServer.sendContent_P(PSTR("                if (('Green' in jsonMessage)) {\n"));
  restServer.sendContent_P(PSTR("                    if (typeof jsonMessage.Green === 'number') {\n"));
  restServer.sendContent_P(PSTR("                        newGreen = jsonMessage.Green\n"));
  restServer.sendContent_P(PSTR("                    }\n"));
  restServer.sendContent_P(PSTR("                }\n"));
  restServer.sendContent_P(PSTR("                if (('Blue' in jsonMessage)) {\n"));
  restServer.sendContent_P(PSTR("                    if (typeof jsonMessage.Blue === 'number') {\n"));
  restServer.sendContent_P(PSTR("                        newBlue = jsonMessage.Blue\n"));
  restServer.sendContent_P(PSTR("                    }\n"));
  restServer.sendContent_P(PSTR("                }\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("                // Update button here \n"));
  restServer.sendContent_P(PSTR("                $('#colourButton').css('background-color', 'rgb(' + newRed + ',' + newGreen + ',' + newBlue + ')')\n"));
  restServer.sendContent_P(PSTR("                $('#colourButton').css('color', (0.2126 * newRed + 0.7152 * newGreen + 0.0722 * newBlue > 40) ? '#222' : '#ddd')\n"));
  restServer.sendContent_P(PSTR("                $('#colourButton').val('rgb(' + newRed + ',' + newGreen + ',' + newBlue + ')')\n"));
  restServer.sendContent_P(PSTR("            }\n"));
  restServer.sendContent_P(PSTR("        }\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("        function handleTemperatureMessage(jsonMessage) {\n"));
  restServer.sendContent_P(PSTR("            if (jsonMessage && typeof jsonMessage === 'object' && jsonMessage.constructor === Array) {\n"));
  restServer.sendContent_P(PSTR("                // Set the Label value to the latest\n"));
  restServer.sendContent_P(PSTR("                $('#tempLabel').html(parseFloat(Math.round(jsonMessage[0].y * 100) / 100).toFixed(1))\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("                // Update the x axis range\n"));
  restServer.sendContent_P(PSTR("                temperatureScatter.options.scales.xAxes[0].ticks.max = jsonMessage[0].x\n"));
  restServer.sendContent_P(PSTR("                temperatureScatter.options.scales.xAxes[0].ticks.min = jsonMessage[jsonMessage.length - 1].x\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("                // Update the y axis range\n"));
  restServer.sendContent_P(PSTR("                let minValue = jsonMessage[0].y\n"));
  restServer.sendContent_P(PSTR("                let maxValue = jsonMessage[0].y\n"));
  restServer.sendContent_P(PSTR("                jsonMessage.forEach((dataPoint) => {\n"));
  restServer.sendContent_P(PSTR("                    minValue = (dataPoint.y < minValue) ? dataPoint.y : minValue\n"));
  restServer.sendContent_P(PSTR("                    maxValue = (dataPoint.y > maxValue) ? dataPoint.y : maxValue\n"));
  restServer.sendContent_P(PSTR("                })\n"));
  restServer.sendContent_P(PSTR("                temperatureScatter.options.scales.yAxes[0].ticks.min = minValue - 3\n"));
  restServer.sendContent_P(PSTR("                temperatureScatter.options.scales.yAxes[0].ticks.max = maxValue + 3\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("                // Update the chart data \n"));
  restServer.sendContent_P(PSTR("                temperatureScatter.data.datasets.forEach((dataset) => {\n"));
  restServer.sendContent_P(PSTR("                    if (dataset.label == 'Temperature') {\n"));
  restServer.sendContent_P(PSTR("                        dataset.data = jsonMessage\n"));
  restServer.sendContent_P(PSTR("                        temperatureScatter.update()\n"));
  restServer.sendContent_P(PSTR("                    }\n"));
  restServer.sendContent_P(PSTR("                })\n"));
  restServer.sendContent_P(PSTR("            }\n"));
  restServer.sendContent_P(PSTR("        }\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("        function handleHumidityMessage(jsonMessage) {\n"));
  restServer.sendContent_P(PSTR("            if (jsonMessage && typeof jsonMessage === 'object' && jsonMessage.constructor === Array) {\n"));
  restServer.sendContent_P(PSTR("                // Set the Label value to the latest\n"));
  restServer.sendContent_P(PSTR("                $('#humidityLabel').html(parseFloat(Math.round(jsonMessage[0].y * 100) / 100).toFixed(0))\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("                // Update the x axis range\n"));
  restServer.sendContent_P(PSTR("                humidityScatter.options.scales.xAxes[0].ticks.max = jsonMessage[0].x\n"));
  restServer.sendContent_P(PSTR("                humidityScatter.options.scales.xAxes[0].ticks.min = jsonMessage[jsonMessage.length - 1].x\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("                // Update the y axis range\n"));
  restServer.sendContent_P(PSTR("                let minValue = jsonMessage[0].y\n"));
  restServer.sendContent_P(PSTR("                let maxValue = jsonMessage[0].y\n"));
  restServer.sendContent_P(PSTR("                jsonMessage.forEach((dataPoint) => {\n"));
  restServer.sendContent_P(PSTR("                    minValue = (dataPoint.y < minValue) ? dataPoint.y : minValue\n"));
  restServer.sendContent_P(PSTR("                    maxValue = (dataPoint.y > maxValue) ? dataPoint.y : maxValue\n"));
  restServer.sendContent_P(PSTR("                })\n"));
  restServer.sendContent_P(PSTR("                humidityScatter.options.scales.yAxes[0].ticks.min = (minValue > 0) ? minValue - 3 : 0\n"));
  restServer.sendContent_P(PSTR("                humidityScatter.options.scales.yAxes[0].ticks.max = (maxValue < 100) ? maxValue + 3 : 100\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("                // Update the chart\n"));
  restServer.sendContent_P(PSTR("                humidityScatter.data.datasets.forEach((dataset) => {\n"));
  restServer.sendContent_P(PSTR("                    if (dataset.label == 'Humidity') {\n"));
  restServer.sendContent_P(PSTR("                        dataset.data = jsonMessage\n"));
  restServer.sendContent_P(PSTR("                        humidityScatter.update()\n"));
  restServer.sendContent_P(PSTR("                    }\n"));
  restServer.sendContent_P(PSTR("                })\n"));
  restServer.sendContent_P(PSTR("            }\n"));
  restServer.sendContent_P(PSTR("        }\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("        function handleMoistureMessage(jsonMessage) {\n"));
  restServer.sendContent_P(PSTR("            if (typeof jsonMessage === 'number' && isFinite(jsonMessage)) {\n"));
  restServer.sendContent_P(PSTR("                // Set the Label value to the latest\n"));
  restServer.sendContent_P(PSTR("                $('#moistureLabel').html(parseFloat(Math.round(jsonMessage * 100) / 100).toFixed(0))\n"));
  restServer.sendContent_P(PSTR("            }\n"));
  restServer.sendContent_P(PSTR("        }\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("        function sendMessage(jsonMessage) {\n"));
  restServer.sendContent_P(PSTR("            // console.log('Sending: ' + JSON.stringify(jsonMessage))\n"));
  restServer.sendContent_P(PSTR("            if (websock != null && websock.readyState == 1) {\n"));
  restServer.sendContent_P(PSTR("                websock.send(JSON.stringify(jsonMessage));\n"));
  restServer.sendContent_P(PSTR("            } else {\n"));
  restServer.sendContent_P(PSTR("                alert('Websockets are currently closed!')\n"));
  restServer.sendContent_P(PSTR("                console.warn('Websockets are closed')\n"));
  restServer.sendContent_P(PSTR("            }\n"));
  restServer.sendContent_P(PSTR("        }\n"));
  restServer.sendContent_P(PSTR("    </script>\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("</head>\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("<body class='text-justify text-center' onload='javascript:onStart();'>\n"));
  restServer.sendContent_P(PSTR("    <div class='cover-container d-flex w-100 h-100 p-3 mx-auto flex-column'>\n"));
  restServer.sendContent_P(PSTR("        <header class='masthead mb-auto'>\n"));
  restServer.sendContent_P(PSTR("            <div class='inner'>\n"));
  restServer.sendContent_P(PSTR("                <h3 class='masthead-brand'>IoTerrium</h3>\n"));
  restServer.sendContent_P(PSTR("                <nav class='nav nav-masthead justify-content-center mb-3'>\n"));
  restServer.sendContent_P(PSTR("                    <a class='nav-link active' href='#'>Home</a>\n"));
  restServer.sendContent_P(PSTR("                    <a class='nav-link' href='https://github.com/thebigpotatoe/Iot-Terrarium'>Instructables</a>\n"));
  restServer.sendContent_P(PSTR("                    <a class='nav-link' href='https://github.com/thebigpotatoe/Iot-Terrarium'>GitHub</a>\n"));
  restServer.sendContent_P(PSTR("                </nav>\n"));
  restServer.sendContent_P(PSTR("            </div>\n"));
  restServer.sendContent_P(PSTR("        </header>\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("        <main role='main' class='inner cover'>\n"));
  restServer.sendContent_P(PSTR("            <div class='row'>\n"));
  restServer.sendContent_P(PSTR("                <div class='col-lg-3'>\n"));
  restServer.sendContent_P(PSTR("                    <div id='stateButton' class='card mb-3'>\n"));
  restServer.sendContent_P(PSTR("                        <div class='card-body text-center'>\n"));
  restServer.sendContent_P(PSTR("                            <p class='card-text'><b id='stateLabel'>Turn On LED</b></p>\n"));
  restServer.sendContent_P(PSTR("                        </div>\n"));
  restServer.sendContent_P(PSTR("                    </div>\n"));
  restServer.sendContent_P(PSTR("                    <div id='colourButton' class='card mb-3'>\n"));
  restServer.sendContent_P(PSTR("                        <div class='card-body text-center'>\n"));
  restServer.sendContent_P(PSTR("                            <p class='card-text'><b id='colourLabel'>Choose Colour</b></p>\n"));
  restServer.sendContent_P(PSTR("                        </div>\n"));
  restServer.sendContent_P(PSTR("                    </div>\n"));
  restServer.sendContent_P(PSTR("                    <div class='card mb-3'>\n"));
  restServer.sendContent_P(PSTR("                        <div class='card-body text-center'>\n"));
  restServer.sendContent_P(PSTR("                            <p class='card-text'>Temperature is <a><b id='tempLabel'>-</b></a>&#8451</p>\n"));
  restServer.sendContent_P(PSTR("                        </div>\n"));
  restServer.sendContent_P(PSTR("                    </div>\n"));
  restServer.sendContent_P(PSTR("                    <div class='card mb-3'>\n"));
  restServer.sendContent_P(PSTR("                        <div class='card-body text-center'>\n"));
  restServer.sendContent_P(PSTR("                            <p class='card-text'>Humidity is <a><b id='humidityLabel'>-</b></a>%</p>\n"));
  restServer.sendContent_P(PSTR("                        </div>\n"));
  restServer.sendContent_P(PSTR("                    </div>\n"));
  restServer.sendContent_P(PSTR("                    <div class='card mb-3'>\n"));
  restServer.sendContent_P(PSTR("                        <div class='card-body text-center'>\n"));
  restServer.sendContent_P(PSTR("                            <p class='card-text'>Soil Moisture is <a><b id='moistureLabel'>-</b></a>%</p>\n"));
  restServer.sendContent_P(PSTR("                        </div>\n"));
  restServer.sendContent_P(PSTR("                    </div>\n"));
  restServer.sendContent_P(PSTR("                    <div class='card mb-3'>\n"));
  restServer.sendContent_P(PSTR("                        <div class='card-body text-center'>\n"));
  restServer.sendContent_P(PSTR("                            <p class='card-text'>Websockets are <a><b id='wsState'>closed</b></a></p>\n"));
  restServer.sendContent_P(PSTR("                        </div>\n"));
  restServer.sendContent_P(PSTR("                    </div>\n"));
  restServer.sendContent_P(PSTR("                </div>\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("                <div class='col-lg-9 mb-3'>\n"));
  restServer.sendContent_P(PSTR("                    <div class='card-deck' style='height: 100%;'>\n"));
  restServer.sendContent_P(PSTR("                        <div class='card border-light p-3' style='background-color: transparent;'>\n"));
  restServer.sendContent_P(PSTR("                            <canvas id='temperatureChart' style='width:100%; height:100%;'></canvas>\n"));
  restServer.sendContent_P(PSTR("                        </div>\n"));
  restServer.sendContent_P(PSTR("                        <div class='card border-light p-3' style='background-color: transparent;'>\n"));
  restServer.sendContent_P(PSTR("                            <canvas id='humidityChart' style='width:100%; height:100%;'></canvas>\n"));
  restServer.sendContent_P(PSTR("                        </div>\n"));
  restServer.sendContent_P(PSTR("                    </div>\n"));
  restServer.sendContent_P(PSTR("                </div>\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("                <script>\n"));
  restServer.sendContent_P(PSTR("                    var colourDebounce = Date.now()\n"));
  restServer.sendContent_P(PSTR("                    var lastMessage = ''\n"));
  restServer.sendContent_P(PSTR("                    let currentRed = 0\n"));
  restServer.sendContent_P(PSTR("                    let currentGreen = 0\n"));
  restServer.sendContent_P(PSTR("                    let currentBlue = 0\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("                    $('#stateButton').click(function () {\n"));
  restServer.sendContent_P(PSTR("                        var newState = $('#stateButton').val() == 'ON' ? 'OFF' : 'ON'\n"));
  restServer.sendContent_P(PSTR("                        onStateButtonEvent(newState)\n"));
  restServer.sendContent_P(PSTR("                    });\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("                    function onStateButtonEvent(currentState) {\n"));
  restServer.sendContent_P(PSTR("                        if (currentState != $('#stateButton').val()) {\n"));
  restServer.sendContent_P(PSTR("                            if (currentState === 'OFF') {\n"));
  restServer.sendContent_P(PSTR("                                msgValue = false\n"));
  restServer.sendContent_P(PSTR("                                $('#stateButton').val('OFF')\n"));
  restServer.sendContent_P(PSTR("                                $('#stateLabel').html('Turn On LED')\n"));
  restServer.sendContent_P(PSTR("                            } else if (currentState === 'ON') {\n"));
  restServer.sendContent_P(PSTR("                                msgValue = true\n"));
  restServer.sendContent_P(PSTR("                                $('#stateButton').val('ON')\n"));
  restServer.sendContent_P(PSTR("                                $('#stateLabel').html('Turn Off LED')\n"));
  restServer.sendContent_P(PSTR("                            }\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("                            msg = {\n"));
  restServer.sendContent_P(PSTR("                                'State': msgValue\n"));
  restServer.sendContent_P(PSTR("                            }\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("                            sendMessage(msg)\n"));
  restServer.sendContent_P(PSTR("                        }\n"));
  restServer.sendContent_P(PSTR("                    }\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("                    $('#colourButton').colorPicker({\n"));
  restServer.sendContent_P(PSTR("                        customBG: '#222',\n"));
  restServer.sendContent_P(PSTR("                        margin: '4px -2px 0',\n"));
  restServer.sendContent_P(PSTR("                        doRender: 'div div',\n"));
  restServer.sendContent_P(PSTR("                        preventFocus: true,\n"));
  restServer.sendContent_P(PSTR("                        animationSpeed: 150,\n"));
  restServer.sendContent_P(PSTR("                        forceAlpha: false,\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("                        buildCallback: function ($elm) {\n"));
  restServer.sendContent_P(PSTR("                            this.$colorPatch = $elm.prepend('<div class=\\\'cp-disp\\\'>').find('.cp-disp');\n"));
  restServer.sendContent_P(PSTR("                        },\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("                        cssAddon: '.cp-color-picker {width:80%; height: 50%}' +\n"));
  restServer.sendContent_P(PSTR("                            '@media screen and (min-width: 992px) {.cp-color-picker {width:22%; height: 50%}}' +\n"));
  restServer.sendContent_P(PSTR("                            '@media screen and (min-width: 1275px) {.cp-color-picker {width:280px; height: 50%}}' +\n"));
  restServer.sendContent_P(PSTR("                            '.cp-disp {padding:5px; margin-bottom:4px; font-size:95%; height:10%; line-height:20px}' +\n"));
  restServer.sendContent_P(PSTR("                            '.cp-xy-slider {height:87%; width:77%;}' +\n"));
  restServer.sendContent_P(PSTR("                            '.cp-z-slider {height:87%; width:20%;}' +\n"));
  restServer.sendContent_P(PSTR("                            '.cp-xy-cursor {width:16px; height:16px; border-width:2px; margin:-8px}' +\n"));
  restServer.sendContent_P(PSTR("                            '.cp-z-cursor {border-width:8px; margin-top:-8px;}' +\n"));
  restServer.sendContent_P(PSTR("                            '.cp-alpha {height:0px;}',\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("                        renderCallback: function ($elm, toggled) {\n"));
  restServer.sendContent_P(PSTR("                            var colors = this.color.colors;\n"));
  restServer.sendContent_P(PSTR("                            this.$colorPatch.css({\n"));
  restServer.sendContent_P(PSTR("                                backgroundColor: '#' + colors.HEX,\n"));
  restServer.sendContent_P(PSTR("                                color: colors.RGBLuminance > 0.22 ? '#222' : '#ddd'\n"));
  restServer.sendContent_P(PSTR("                            }).text(this.color.toString($elm._colorMode)); // $elm.val();   \n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("                            onColourButtonEvent(Math.round(colors.rgb.r * 255), Math.round(colors.rgb.g * 255), Math.round(colors.rgb.b * 255))\n"));
  restServer.sendContent_P(PSTR("                        }\n"));
  restServer.sendContent_P(PSTR("                    })\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("                    function onColourButtonEvent(red, green, blue) {\n"));
  restServer.sendContent_P(PSTR("                        if (currentRed != red || currentGreen != green || currentBlue != blue) {\n"));
  restServer.sendContent_P(PSTR("                            currentRed = red\n"));
  restServer.sendContent_P(PSTR("                            currentGreen = green\n"));
  restServer.sendContent_P(PSTR("                            currentBlue = blue\n"));
  restServer.sendContent_P(PSTR("                            let state = (red === 0 && green === 0 && blue === 0) ? false : true\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("                            msg = {\n"));
  restServer.sendContent_P(PSTR("                                'State': state,\n"));
  restServer.sendContent_P(PSTR("                                'Colour': {\n"));
  restServer.sendContent_P(PSTR("                                    'Red': red,\n"));
  restServer.sendContent_P(PSTR("                                    'Green': green,\n"));
  restServer.sendContent_P(PSTR("                                    'Blue': blue\n"));
  restServer.sendContent_P(PSTR("                                }\n"));
  restServer.sendContent_P(PSTR("                            }\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("                            if (Date.now() - colourDebounce > 50 && lastMessage !== msg) {\n"));
  restServer.sendContent_P(PSTR("                                lastMessage = msg\n"));
  restServer.sendContent_P(PSTR("                                colourDebounce = Date.now()\n"));
  restServer.sendContent_P(PSTR("                                sendMessage(msg)\n"));
  restServer.sendContent_P(PSTR("                            }\n"));
  restServer.sendContent_P(PSTR("                        }\n"));
  restServer.sendContent_P(PSTR("                    }\n"));
  restServer.sendContent_P(PSTR("                </script>\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("                <script>\n"));
  restServer.sendContent_P(PSTR("                    Chart.defaults.global.defaultFontColor = '#FFF'\n"));
  restServer.sendContent_P(PSTR("                    Chart.defaults.global.animation.easing = 'easeInOutQuint'\n"));
  restServer.sendContent_P(PSTR("                    Chart.defaults.global.animation.duration = 0\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("                    var temperatureChartElement = document.getElementById('temperatureChart');\n"));
  restServer.sendContent_P(PSTR("                    var temperatureScatter = new Chart(temperatureChartElement, {\n"));
  restServer.sendContent_P(PSTR("                        type: 'scatter',\n"));
  restServer.sendContent_P(PSTR("                        data: {\n"));
  restServer.sendContent_P(PSTR("                            datasets: [{\n"));
  restServer.sendContent_P(PSTR("                                label: 'Temperature',\n"));
  restServer.sendContent_P(PSTR("                                lineTension: 0.5,\n"));
  restServer.sendContent_P(PSTR("                                borderColor: '#fff',\n"));
  restServer.sendContent_P(PSTR("                                showLine: true,\n"));
  restServer.sendContent_P(PSTR("                                borderWidth: 2.5\n"));
  restServer.sendContent_P(PSTR("                            }]\n"));
  restServer.sendContent_P(PSTR("                        },\n"));
  restServer.sendContent_P(PSTR("                        options: {\n"));
  restServer.sendContent_P(PSTR("                            responsive: false,\n"));
  restServer.sendContent_P(PSTR("                            title: {\n"));
  restServer.sendContent_P(PSTR("                                display: true,\n"));
  restServer.sendContent_P(PSTR("                                text: 'Temperature'\n"));
  restServer.sendContent_P(PSTR("                            },\n"));
  restServer.sendContent_P(PSTR("                            legend: {\n"));
  restServer.sendContent_P(PSTR("                                display: false\n"));
  restServer.sendContent_P(PSTR("                            },\n"));
  restServer.sendContent_P(PSTR("                            tooltips: {\n"));
  restServer.sendContent_P(PSTR("                                mode: 'label',\n"));
  restServer.sendContent_P(PSTR("                            },\n"));
  restServer.sendContent_P(PSTR("                            hover: {\n"));
  restServer.sendContent_P(PSTR("                                mode: 'nearest',\n"));
  restServer.sendContent_P(PSTR("                                intersect: true\n"));
  restServer.sendContent_P(PSTR("                            },\n"));
  restServer.sendContent_P(PSTR("                            elements: {\n"));
  restServer.sendContent_P(PSTR("                                point: {\n"));
  restServer.sendContent_P(PSTR("                                    radius: 0\n"));
  restServer.sendContent_P(PSTR("                                }\n"));
  restServer.sendContent_P(PSTR("                            },\n"));
  restServer.sendContent_P(PSTR("                            scales: {\n"));
  restServer.sendContent_P(PSTR("                                xAxes: [{\n"));
  restServer.sendContent_P(PSTR("                                    display: true,\n"));
  restServer.sendContent_P(PSTR("                                    gridLines: {\n"));
  restServer.sendContent_P(PSTR("                                        display: true,\n"));
  restServer.sendContent_P(PSTR("                                        color: '#666'\n"));
  restServer.sendContent_P(PSTR("                                    },\n"));
  restServer.sendContent_P(PSTR("                                    scaleLabel: {\n"));
  restServer.sendContent_P(PSTR("                                        display: true,\n"));
  restServer.sendContent_P(PSTR("                                        labelString: 'Time'\n"));
  restServer.sendContent_P(PSTR("                                    },\n"));
  restServer.sendContent_P(PSTR("                                    ticks: {\n"));
  restServer.sendContent_P(PSTR("                                        maxTicksLimit: 10,\n"));
  restServer.sendContent_P(PSTR("                                        callback: function (value, index, values) {\n"));
  restServer.sendContent_P(PSTR("                                            var now = new Date()\n"));
  restServer.sendContent_P(PSTR("                                            var date = new Date(value * 1000 + now.getTimezoneOffset() * 60000);\n"));
  restServer.sendContent_P(PSTR("                                            var hours = date.getHours();\n"));
  restServer.sendContent_P(PSTR("                                            var minutes = '0' + date.getMinutes();\n"));
  restServer.sendContent_P(PSTR("                                            var seconds = '0' + date.getSeconds();\n"));
  restServer.sendContent_P(PSTR("                                            var formattedTime = hours + ':' + minutes.substr(-2);\n"));
  restServer.sendContent_P(PSTR("                                            return formattedTime;\n"));
  restServer.sendContent_P(PSTR("                                        }\n"));
  restServer.sendContent_P(PSTR("                                    },\n"));
  restServer.sendContent_P(PSTR("                                    afterTickToLabelConversion: function (scaleInstance) {\n"));
  restServer.sendContent_P(PSTR("                                        scaleInstance.ticks[0] = null;\n"));
  restServer.sendContent_P(PSTR("                                        scaleInstance.ticks[scaleInstance.ticks.length - 1] = null;\n"));
  restServer.sendContent_P(PSTR("                                        scaleInstance.ticksAsNumbers[0] = null;\n"));
  restServer.sendContent_P(PSTR("                                        scaleInstance.ticksAsNumbers[scaleInstance.ticksAsNumbers.length - 1] = null;\n"));
  restServer.sendContent_P(PSTR("                                    }\n"));
  restServer.sendContent_P(PSTR("                                }],\n"));
  restServer.sendContent_P(PSTR("                                yAxes: [{\n"));
  restServer.sendContent_P(PSTR("                                    display: true,\n"));
  restServer.sendContent_P(PSTR("                                    gridLines: {\n"));
  restServer.sendContent_P(PSTR("                                        display: false,\n"));
  restServer.sendContent_P(PSTR("                                        color: '#666'\n"));
  restServer.sendContent_P(PSTR("                                    },\n"));
  restServer.sendContent_P(PSTR("                                    scaleLabel: {\n"));
  restServer.sendContent_P(PSTR("                                        display: true,\n"));
  restServer.sendContent_P(PSTR("                                        labelString: ('Temperature (' + String.fromCharCode(8451) + ')')\n"));
  restServer.sendContent_P(PSTR("                                    },\n"));
  restServer.sendContent_P(PSTR("                                    afterTickToLabelConversion: function (scaleInstance) {\n"));
  restServer.sendContent_P(PSTR("                                        scaleInstance.ticks[0] = null;\n"));
  restServer.sendContent_P(PSTR("                                        scaleInstance.ticks[scaleInstance.ticks.length - 1] = null;\n"));
  restServer.sendContent_P(PSTR("                                        scaleInstance.ticksAsNumbers[0] = null;\n"));
  restServer.sendContent_P(PSTR("                                        scaleInstance.ticksAsNumbers[scaleInstance.ticksAsNumbers.length - 1] = null;\n"));
  restServer.sendContent_P(PSTR("                                    }\n"));
  restServer.sendContent_P(PSTR("                                }]\n"));
  restServer.sendContent_P(PSTR("                            }\n"));
  restServer.sendContent_P(PSTR("                        }\n"));
  restServer.sendContent_P(PSTR("                    });\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("                    var humidityChartElement = document.getElementById('humidityChart');\n"));
  restServer.sendContent_P(PSTR("                    var humidityScatter = new Chart(humidityChartElement, {\n"));
  restServer.sendContent_P(PSTR("                        type: 'scatter',\n"));
  restServer.sendContent_P(PSTR("                        data: {\n"));
  restServer.sendContent_P(PSTR("                            datasets: [{\n"));
  restServer.sendContent_P(PSTR("                                label: 'Humidity',\n"));
  restServer.sendContent_P(PSTR("                                lineTension: 0.5,\n"));
  restServer.sendContent_P(PSTR("                                borderColor: '#fff',\n"));
  restServer.sendContent_P(PSTR("                                showLine: true,\n"));
  restServer.sendContent_P(PSTR("                                borderWidth: 2.5\n"));
  restServer.sendContent_P(PSTR("                            }]\n"));
  restServer.sendContent_P(PSTR("                        },\n"));
  restServer.sendContent_P(PSTR("                        options: {\n"));
  restServer.sendContent_P(PSTR("                            responsive: false,\n"));
  restServer.sendContent_P(PSTR("                            title: {\n"));
  restServer.sendContent_P(PSTR("                                display: true,\n"));
  restServer.sendContent_P(PSTR("                                text: 'Humidity'\n"));
  restServer.sendContent_P(PSTR("                            },\n"));
  restServer.sendContent_P(PSTR("                            legend: {\n"));
  restServer.sendContent_P(PSTR("                                display: false\n"));
  restServer.sendContent_P(PSTR("                            },\n"));
  restServer.sendContent_P(PSTR("                            tooltips: {\n"));
  restServer.sendContent_P(PSTR("                                mode: 'label',\n"));
  restServer.sendContent_P(PSTR("                            },\n"));
  restServer.sendContent_P(PSTR("                            hover: {\n"));
  restServer.sendContent_P(PSTR("                                mode: 'nearest',\n"));
  restServer.sendContent_P(PSTR("                                intersect: true\n"));
  restServer.sendContent_P(PSTR("                            },\n"));
  restServer.sendContent_P(PSTR("                            elements: {\n"));
  restServer.sendContent_P(PSTR("                                point: {\n"));
  restServer.sendContent_P(PSTR("                                    radius: 0\n"));
  restServer.sendContent_P(PSTR("                                }\n"));
  restServer.sendContent_P(PSTR("                            },\n"));
  restServer.sendContent_P(PSTR("                            scales: {\n"));
  restServer.sendContent_P(PSTR("                                xAxes: [{\n"));
  restServer.sendContent_P(PSTR("                                    display: true,\n"));
  restServer.sendContent_P(PSTR("                                    gridLines: {\n"));
  restServer.sendContent_P(PSTR("                                        display: true,\n"));
  restServer.sendContent_P(PSTR("                                        color: '#666'\n"));
  restServer.sendContent_P(PSTR("                                    },\n"));
  restServer.sendContent_P(PSTR("                                    scaleLabel: {\n"));
  restServer.sendContent_P(PSTR("                                        display: true,\n"));
  restServer.sendContent_P(PSTR("                                        labelString: 'Time'\n"));
  restServer.sendContent_P(PSTR("                                    },\n"));
  restServer.sendContent_P(PSTR("                                    ticks: {\n"));
  restServer.sendContent_P(PSTR("                                        maxTicksLimit: 10,\n"));
  restServer.sendContent_P(PSTR("                                        callback: function (value, index, values) {\n"));
  restServer.sendContent_P(PSTR("                                            var now = new Date()\n"));
  restServer.sendContent_P(PSTR("                                            var date = new Date(value * 1000 + now\n"));
  restServer.sendContent_P(PSTR("                                                .getTimezoneOffset() * 60000);\n"));
  restServer.sendContent_P(PSTR("                                            var hours = date.getHours();\n"));
  restServer.sendContent_P(PSTR("                                            var minutes = '0' + date.getMinutes();\n"));
  restServer.sendContent_P(PSTR("                                            var seconds = '0' + date.getSeconds();\n"));
  restServer.sendContent_P(PSTR("                                            var formattedTime = hours + ':' + minutes.substr(-2);\n"));
  restServer.sendContent_P(PSTR("                                            return formattedTime;\n"));
  restServer.sendContent_P(PSTR("                                        }\n"));
  restServer.sendContent_P(PSTR("                                    },\n"));
  restServer.sendContent_P(PSTR("                                    afterTickToLabelConversion: function (scaleInstance) {\n"));
  restServer.sendContent_P(PSTR("                                        scaleInstance.ticks[0] = null;\n"));
  restServer.sendContent_P(PSTR("                                        scaleInstance.ticks[scaleInstance.ticks.length - 1] = null;\n"));
  restServer.sendContent_P(PSTR("                                        scaleInstance.ticksAsNumbers[0] = null;\n"));
  restServer.sendContent_P(PSTR("                                        scaleInstance.ticksAsNumbers[scaleInstance.ticksAsNumbers.length - 1] = null;\n"));
  restServer.sendContent_P(PSTR("                                    }\n"));
  restServer.sendContent_P(PSTR("                                }],\n"));
  restServer.sendContent_P(PSTR("                                yAxes: [{\n"));
  restServer.sendContent_P(PSTR("                                    display: true,\n"));
  restServer.sendContent_P(PSTR("                                    gridLines: {\n"));
  restServer.sendContent_P(PSTR("                                        display: false,\n"));
  restServer.sendContent_P(PSTR("                                        color: '#666'\n"));
  restServer.sendContent_P(PSTR("                                    },\n"));
  restServer.sendContent_P(PSTR("                                    scaleLabel: {\n"));
  restServer.sendContent_P(PSTR("                                        display: true,\n"));
  restServer.sendContent_P(PSTR("                                        labelString: 'Humidity (%)'\n"));
  restServer.sendContent_P(PSTR("                                    },\n"));
  restServer.sendContent_P(PSTR("                                    afterTickToLabelConversion: function (scaleInstance) {\n"));
  restServer.sendContent_P(PSTR("                                        scaleInstance.ticks[0] = null;\n"));
  restServer.sendContent_P(PSTR("                                        scaleInstance.ticks[scaleInstance.ticks.length - 1] = null;\n"));
  restServer.sendContent_P(PSTR("                                        scaleInstance.ticksAsNumbers[0] = null;\n"));
  restServer.sendContent_P(PSTR("                                        scaleInstance.ticksAsNumbers[scaleInstance.ticksAsNumbers.length - 1] = null;\n"));
  restServer.sendContent_P(PSTR("                                    }\n"));
  restServer.sendContent_P(PSTR("                                }]\n"));
  restServer.sendContent_P(PSTR("                            }\n"));
  restServer.sendContent_P(PSTR("                        }\n"));
  restServer.sendContent_P(PSTR("                    });\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("                </script>\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("            </div>\n"));
  restServer.sendContent_P(PSTR("        </main>\n"));
  restServer.sendContent_P(PSTR("\n"));
  restServer.sendContent_P(PSTR("        <footer class='mastfoot mt-auto'>\n"));
  restServer.sendContent_P(PSTR("            <div class='inner'>\n"));
  restServer.sendContent_P(PSTR("                <p>An <a href='https://getbootstrap.com/'>Instructable</a> project by <a\n"));
  restServer.sendContent_P(PSTR("                        href='https://www.instructables.com/member/thebigpotatoe/'>Thebigpotatoe</a>\n"));
  restServer.sendContent_P(PSTR("                    | Cover template for <a href='https://getbootstrap.com/'>Bootstrap</a>, by <a\n"));
  restServer.sendContent_P(PSTR("                        href='https://twitter.com/mdo'>@mdo</a>\n"));
  restServer.sendContent_P(PSTR("                    | Icons made by <a href='https://www.flaticon.com/authors/darius-dan' title='Darius Dan'>Darius\n"));
  restServer.sendContent_P(PSTR("                        Dan</a> from <a href='https://www.flaticon.com/' title='Flaticon'>flaticon</a></p>\n"));
  restServer.sendContent_P(PSTR("            </div>\n"));
  restServer.sendContent_P(PSTR("        </footer>\n"));
  restServer.sendContent_P(PSTR("    </div>\n"));
  restServer.sendContent_P(PSTR("</body>\n"));

  restServer.sendContent("");
  restServer.client().stop();
}